Config = {}

Config.AbertoAll = false
Config.TotalGaragem = 3
Config.Veiculos = {
    {
        categoria = {title="Carros Nacionais", id="carros"},
        veiculos = {
            {title = "blista", model="blista", mala=40, preco=30000, estoque = 20},                                                                      
            {title = "brioso", model="brioso", mala=30, preco=45000, estoque = 20},                                                                      
            {title = "dilettante", model="dilettante", mala=50, preco=30000, estoque = 15},                                                                      
            {title = "kanjo", model="kanjo", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "issi2", model="issi2", mala=50, preco=45000, estoque = 15},                                                                      
            {title = "panto", model="panto", mala=20, preco=20000, estoque = 25},                                                                      
            {title = "prairie", model="prairie", mala=25, preco=30000, estoque = 15},                                                                      
            {title = "rhapsody", model="rhapsody", mala=30, preco=25000, estoque = 15},                                                                      
            {title = "cogcabrio", model="cogcabrio", mala=60, preco=45000, estoque = 15},                                                                      
            {title = "exemplar", model="exemplar", mala=20, preco=70000, estoque = 15},                                                                      
            {title = "f620", model="f620", mala=30, preco=45000, estoque = 15},                                                                      
            {title = "felon", model="felon", mala=50, preco=50000, estoque = 15},                                                                      
            {title = "jackal", model="jackal", mala=30, preco=65000, estoque = 15},                                                                      
            {title = "oracle", model="oracle", mala=50, preco=40000, estoque = 15},                                                                      
            {title = "oracle2", model="oracle2", mala=60, preco=55000, estoque = 15},                                                                      
            {title = "sentinel", model="sentinel", mala=40, preco=50000, estoque = 15},                                                                      
            {title = "windsor", model="windsor", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "zion", model="zion", mala=40, preco=50000, estoque = 15},                                                                      
            {title = "blade", model="blade", mala=40, preco=70000, estoque = 15},                                                                      
            {title = "buccaneer", model="buccaneer", mala=50, preco=65000, estoque = 15},                                                                      
            {title = "buccaneer2", model="buccaneer2", mala=60, preco=55000, estoque = 15},                                                                      
            {title = "chino", model="chino", mala=50, preco=55000, estoque = 15},                                                                      
            {title = "chino2", model="chino2", mala=60, preco=85000, estoque = 15},                                                                      
            {title = "coquette3", model="coquette3", mala=00, preco=85000, estoque = 15},                                                                      
            {title = "dominator", model="dominator", mala=50, preco=55000, estoque = 15},                                                                      
            {title = "dominator3", model="dominator3", mala=30, preco=100000, estoque = 15},                                                                      
            {title = "dukes", model="dukes", mala=40, preco=50000, estoque = 15},                                                                      
            {title = "faction", model="faction", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "faction2", model="faction2", mala=40, preco=50000, estoque = 15},                                                                      
            {title = "ellie", model="ellie", mala=50, preco=55000, estoque = 15},                                                                      
            {title = "gauntlet", model="gauntlet", mala=40, preco=65000, estoque = 15},                                                                      
            {title = "hermes", model="hermes", mala=70, preco=70000, estoque = 15},                                                                      
            {title = "hotknife", model="hotknife", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "hustler", model="hustler", mala=00, preco=70000, estoque = 15},                                                                      
            {title = "picador", model="picador", mala=90, preco=85000, estoque = 15},                                                                      
            {title = "ratloader2", model="ratloader2", mala=70, preco=85000, estoque = 15},                                                                      
            {title = "ruiner2", model="ruiner2", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "slamvan3", model="slamvan3", mala=80, preco=85000, estoque = 15},                                                                      
            {title = "tampa", model="tampa", mala=40, preco=55000, estoque = 15},                                                                      
            {title = "tulip", model="tulip", mala=60, preco=55000, estoque = 15},                                                                      
            {title = "vigero", model="vigero", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "virgo", model="virgo", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "voodoo", model="voodoo", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "mesa3", model="mesa3", mala=30, preco=400000, estoque = 15},                                                                      
            {title = "baller4", model="baller4", mala=30, preco=400000, estoque = 15},                                                                      
            {title = "baller4", model="baller6", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "bjxl", model="bjxl", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "cavalcade", model="cavalcade", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "cavalcade2", model="cavalcade2", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "contender", model="contender", mala=30, preco=600000, estoque = 15},                                                                      
            {title = "dubsta", model="dubsta", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "dubsta2", model="dubsta2", mala=30, preco=400000, estoque = 15},                                                                      
            {title = "fq2", model="fq2", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "gresley", model="gresley", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "habanero", model="habanero", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "huntley", model="huntley", mala=30, preco=300000, estoque = 15},                                                                      
            {title = "landstalker", model="landstalker", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "rocoto", model="rocoto", mala=30, preco=300000, estoque = 15},                                                                      
            {title = "patriot", model="patriot", mala=30, preco=500000, estoque = 15},                                                                      
            {title = "toros", model="toros", mala=30, preco=500000, estoque = 15},                                                                      
            {title = "xls", model="xls", mala=30, preco=300000, estoque = 15},                                                                      
            {title = "xls2", model="xls2", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "asterope", model="asterope", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "cog55", model="cog55", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "cognoscenti", model="cognoscenti", mala=30, preco=135000, estoque = 15},                                                                      
            {title = "emperor", model="emperor", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "fugitive", model="fugitive", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "intruder", model="intruder", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "stafford", model="stafford", mala=30, preco=100000, estoque = 15},                                                                      
            {title = "alpha", model="alpha", mala=30, preco=125000, estoque = 15},                                                                      
            {title = "banshee", model="banshee", mala=30, preco=300000, estoque = 15},                                                                      
            {title = "bestiagts", model="bestiagts", mala=30, preco=300000, estoque = 15},                                                                      
            {title = "buffalo2", model="buffalo2", mala=30, preco=170000, estoque = 15},                                                                      
            {title = "carbonizzare", model="carbonizzare", mala=30, preco=290000, estoque = 15},                                                                      
            {title = "comet2", model="comet2", mala=30, preco=460000, estoque = 15},                                                                      
            {title = "coquette", model="coquette", mala=30, preco=370000, estoque = 15},                                                                      
            {title = "coquette4", model="coquette4", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "deveste", model="deveste", mala=30, preco=570000, estoque = 15},                                                                      
            {title = "elegy", model="elegy", mala=30, preco=270000, estoque = 15},                                                                      
            {title = "elegy2", model="elegy2", mala=30, preco=370000, estoque = 15},                                                                      
            {title = "flashgt", model="flashgt", mala=30, preco=350000, estoque = 15},                                                                      
            {title = "furoregt", model="furoregt", mala=30, preco=200000, estoque = 15},                                                                      
            {title = "futo", model="futo", mala=30, preco=100000, estoque = 15},                                                                      
            {title = "italigto", model="italigto", mala=30, preco=730000, estoque = 15},                                                                      
            {title = "jester", model="jester", mala=30, preco=420000, estoque = 15},                                                                      
            {title = "khamelion", model="khamelion", mala=30, preco=165000, estoque = 15},                                                                      
            {title = "kuruma", model="kuruma", mala=30, preco=220000, estoque = 15},                                                                      
            {title = "lynx", model="lynx", mala=30, preco=300000, estoque = 15},                                                                      
            {title = "massacro", model="massacro", mala=30, preco=410000, estoque = 15},                                                                      
            {title = "neon", model="neon", mala=30, preco=465000, estoque = 15},                                                                      
            {title = "ninef", model="ninef", mala=30, preco=325000, estoque = 15},                                                                      
            {title = "penumbra", model="penumbra", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "pariah", model="pariah", mala=30, preco=550000, estoque = 15},                                                                      
            {title = "raiden", model="raiden", mala=30, preco=300000, estoque = 15},                                                                      
            {title = "rapidgt", model="rapidgt", mala=30, preco=180000, estoque = 15},                                                                      
            {title = "revolter", model="revolter", mala=30, preco=150000, estoque = 15},                                                                      
            {title = "ruston", model="ruston", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "schwarzer", model="schwarzer", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "sentinel3", model="sentinel3", mala=30, preco=100000, estoque = 15},                                                                      
            {title = "seven70", model="seven70", mala=30, preco=340000, estoque = 15},                                                                      
            {title = "specter", model="specter", mala=30, preco=510000, estoque = 15},                                                                      
            {title = "sugoi", model="sugoi", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "sultan2", model="sultan2", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "adder", model="adder", mala=30, preco=700000, estoque = 15},                                                                                                                                              
            {title = "surano", model="surano", mala=30, preco=315000, estoque = 15},                                                                       
            {title = "banshee2", model="banshee2", mala=30, preco=400000, estoque = 15},                                                                                                                                              
            {title = "bullet", model="bullet", mala=30, preco=280000, estoque = 15},                                                                                                                                              
            {title = "cheetah", model="cheetah", mala=30, preco=575000, estoque = 15},                                                                                                                                              
            {title = "cyclone", model="cyclone", mala=30, preco=335000, estoque = 15},                                                                                                                                              
            {title = "entity2", model="entity2", mala=30, preco=640000, estoque = 15},                                                                                                                                              
            {title = "entityxf", model="entityxf", mala=30, preco=610000, estoque = 15},                                                                                                                                              
            {title = "furia", model="furia", mala=30, preco=75000, estoque = 15},                                                                                                                                              
            {title = "gp1", model="gp1", mala=30, preco=630000, estoque = 15},                                                                                                                                              
            {title = "italigtb", model="italigtb", mala=30, preco=390000, estoque = 15},                                                                                                                                              
            {title = "osiris", model="osiris", mala=30, preco=825000, estoque = 15},                                                                                                                                              
            {title = "nero", model="nero", mala=30, preco=665000, estoque = 15},                                                                                                                                              
            {title = "pfister811", model="pfister811", mala=30, preco=715000, estoque = 15},                                                                                                                                              
            {title = "prototipo", model="prototipo", mala=30, preco=685000, estoque = 15},                                                                                                                                              
            {title = "reaper", model="reaper", mala=30, preco=500000, estoque = 15},                                                                                                                                              
            {title = "sheava", model="sheava", mala=30, preco=580000, estoque = 15},                                                                                                                                              
            {title = "sultanrs", model="sultanrs", mala=30, preco=450000, estoque = 15},                                                                                                                                              
            {title = "t20", model="t20", mala=30, preco=700000, estoque = 15},                                                                                                                                              
            {title = "taipan", model="taipan", mala=30, preco=470000, estoque = 15},                                                                                                                                              
            {title = "tempesta", model="tempesta", mala=30, preco=490000, estoque = 15},                                                                                                                                              
            {title = "turismor", model="turismor", mala=30, preco=510000, estoque = 15},                                                                                                                                              
            {title = "tyrant", model="tyrant", mala=30, preco=540000, estoque = 15},                                                                                                                                              
            {title = "vacca", model="vacca", mala=30, preco=400000, estoque = 15},                                                                                                                                              
            {title = "vagner", model="vagner", mala=30, preco=690000, estoque = 15},                                                                                                                                              
            {title = "visione", model="visione", mala=30, preco=75000, estoque = 15},                                                                                                                                              
            {title = "xa21", model="xa21", mala=30, preco=600000, estoque = 15},                                                                                                                                              
            {title = "zentorno", model="zentorno", mala=30, preco=800000, estoque = 15},                                                                                                                                              
        }
    }, 
	    {
        categoria = {title="Motos", id="motos"},
        veiculos = {
			{title = "akuma", model = "akuma", mala = 10, preco = 100000, estoque = 15},
			{title = "avarus", model = "avarus", mala = 10, preco = 100000, estoque = 15},
			{title = "bagger", model = "bagger", mala = 10, preco = 100000, estoque = 15},
			{title = "bati", model = "bati", mala = 10, preco = 100000, estoque = 15},
			{title = "bati2", model = "bati2", mala = 10, preco = 100000, estoque = 15},
			{title = "bf400", model = "bf400", mala = 10, preco = 100000, estoque = 15},
			{title = "carbonrs", model = "carbonrs", mala = 10, preco = 100000, estoque = 15},
			{title = "chimera", model = "chimera", mala = 10, preco = 100000, estoque = 15},
			{title = "cliffhanger", model = "cliffhanger", mala = 10, preco = 100000, estoque = 15},
			{title = "daemon", model = "daemon", mala = 10, preco = 100000, estoque = 15},
			{title = "daemon2", model = "daemon2", mala = 10, preco = 100000, estoque = 15},
			{title = "defiler", model = "defiler", mala = 10, preco = 100000, estoque = 15},
			{title = "deathbike", model = "deathbike", mala = 10, preco = 100000, estoque = 15},
			{title = "deathbike3", model = "deathbike3", mala = 10, preco = 100000, estoque = 15},
			{title = "stryder", model = "stryder", mala = 10, preco = 100000, estoque = 15},
			{title = "diablous", model = "diablous", mala = 10, preco = 100000, estoque = 15},
			{title = "diablous2", model = "diablous2", mala = 10, preco = 100000, estoque = 15},
			{title = "double", model = "double", mala = 10, preco = 100000, estoque = 15},
			{title = "enduro", model = "enduro", mala = 10, preco = 100000, estoque = 15},
			{title = "esskey", model = "esskey", mala = 10, preco = 100000, estoque = 15},
			{title = "faggio", model = "faggio", mala = 10, preco = 100000, estoque = 15},
			{title = "faggio2", model = "faggio2", mala = 10, preco = 100000, estoque = 15},
			{title = "faggio3", model = "faggio3", mala = 10, preco = 100000, estoque = 15},
			{title = "fcr", model = "fcr", mala = 10, preco = 100000, estoque = 15},
			{title = "fcr2", model = "fcr2", mala = 10, preco = 100000, estoque = 15},
			{title = "gargoyle", model = "gargoyle", mala = 10, preco = 100000, estoque = 15},
			{title = "hakuchou", model = "hakuchou", mala = 10, preco = 100000, estoque = 15},
			{title = "hakuchou2", model = "hakuchou2", mala = 10, preco = 100000, estoque = 15},
			{title = "hexer", model = "hexer", mala = 10, preco = 100000, estoque = 15},
			{title = "innovation", model = "innovation", mala = 10, preco = 100000, estoque = 15},
			{title = "lectro", model = "lectro", mala = 10, preco = 100000, estoque = 15},
			{title = "manchez", model = "manchez", mala = 10, preco = 100000, estoque = 15},
			{title = "nemesis", model = "nemesis", mala = 10, preco = 100000, estoque = 15},
			{title = "nightblade", model = "nightblade", mala = 10, preco = 100000, estoque = 15},
			{title = "pcj", model = "pcj", mala = 10, preco = 100000, estoque = 15},
			{title = "ratbike", model = "ratbike", mala = 10, preco = 100000, estoque = 15},
			{title = "ruffian", model = "ruffian", mala = 10, preco = 100000, estoque = 15},
			{title = "sanchez", model = "sanchez", mala = 10, preco = 100000, estoque = 15},
			{title = "sanchez2", model = "sanchez2", mala = 10, preco = 100000, estoque = 15},
			{title = "sanctus", model = "sanctus", mala = 10, preco = 100000, estoque = 15},
			{title = "sovereign", model = "sovereign", mala = 10, preco = 100000, estoque = 15},
			{title = "thrust", model = "thrust", mala = 10, preco = 100000, estoque = 15},
			{title = "vader", model = "vader", mala = 10, preco = 100000, estoque = 15},
			{title = "vindicator", model = "vindicator", mala = 10, preco = 100000, estoque = 15},
			{title = "vortex", model = "vortex", mala = 10, preco = 100000, estoque = 15},
			{title = "wolfsbane", model = "wolfsbane", mala = 10, preco = 100000, estoque = 15},
			{title = "zombiea", model = "zombiea", mala = 10, preco = 100000, estoque = 15},
			{title = "zombieb", model = "zombieb", mala = 10, preco = 100000, estoque = 15},                                                                                                                                                                                            
        }
    },  
}
function getVeiculo(modelo)
    for i, cat in pairs(Config.Veiculos) do
        for i2, carro in pairs(cat.veiculos) do 
            if carro.model == modelo then
                return carro
            end
        end
    end
end


function getVeiculos()
    local veiculos = {}
    for i, cat in pairs(Config.Veiculos) do
        for i2, carro in pairs(cat.veiculos) do 
            veiculos[carro.model] = carro
        end
    end

    return veiculos
end