Config = {}

Config.AbertoAll = false
Config.TotalGaragem = 5
Config.Veiculos = {
    {
        categoria = {title="Carros Nacionais", id="carros"},
        veiculos = {
            {title = "blista", model="blista", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "brioso", model="brioso", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "dilettante", model="dilettante", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "kanjo", model="kanjo", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "issi2", model="issi2", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "panto", model="panto", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "prairie", model="prairie", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "rhapsody", model="rhapsody", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "cogcabrio", model="cogcabrio", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "exemplar", model="exemplar", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "f620", model="f620", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "felon", model="felon", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "jackal", model="jackal", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "oracle", model="oracle", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "oracle2", model="oracle2", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "sentinel", model="sentinel", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "windsor", model="windsor", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "zion", model="zion", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "blade", model="blade", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "buccaneer", model="buccaneer", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "buccaneer2", model="buccaneer2", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "chino", model="chino", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "chino2", model="chino2", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "coquette3", model="coquette3", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "dominator", model="dominator", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "dominator3", model="dominator3", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "dukes", model="dukes", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "faction", model="faction", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "faction2", model="faction2", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "ellie", model="ellie", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "gauntlet", model="gauntlet", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "hermes", model="hermes", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "hotknife", model="hotknife", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "hustler", model="hustler", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "picador", model="picador", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "ratloader2", model="ratloader2", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "ruiner2", model="ruiner2", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "slamvan3", model="slamvan3", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "tampa", model="tampa", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "tulip", model="tulip", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "vigero", model="vigero", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "virgo", model="virgo", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "voodoo", model="voodoo", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "mesa3", model="mesa3", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "baller4", model="baller4", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "baller4", model="baller6", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "bjxl", model="bjxl", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "cavalcade", model="cavalcade", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "cavalcade2", model="cavalcade2", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "contender", model="contender", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "dubsta", model="dubsta", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "dubsta2", model="dubsta2", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "fq2", model="fq2", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "gresley", model="gresley", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "habanero", model="habanero", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "huntley", model="huntley", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "landstalker", model="landstalker", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "patriot", model="patriot", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "rocoto", model="rocoto", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "toros", model="toros", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "xls", model="xls", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "xls2", model="xls2", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "asterope", model="asterope", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "cog55", model="cog55", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "cognoscenti", model="cognoscenti", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "emperor", model="emperor", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "fugitive", model="fugitive", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "intruder", model="intruder", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "stafford", model="stafford", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "alpha", model="alpha", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "banshee", model="banshee", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "bestiagts", model="bestiagts", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "buffalo2", model="buffalo2", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "carbonizzare", model="carbonizzare", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "comet2", model="comet2", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "coquette", model="coquette", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "coquette4", model="coquette4", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "deveste", model="deveste", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "elegy", model="elegy", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "elegy2", model="elegy2", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "flashgt", model="flashgt", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "furoregt", model="furoregt", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "futo", model="futo", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "italigto", model="italigto", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "jester", model="jester", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "khamelion", model="khamelion", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "kuruma", model="kuruma", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "lynx", model="lynx", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "massacro", model="massacro", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "neon", model="neon", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "ninef", model="ninef", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "pariah", model="pariah", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "penumbra", model="penumbra", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "raiden", model="raiden", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "rapidgt", model="rapidgt", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "revolter", model="revolter", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "ruston", model="ruston", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "schwarzer", model="schwarzer", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "sentinel3", model="sentinel3", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "seven70", model="seven70", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "specter", model="specter", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "sugoi", model="sugoi", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "sultan2", model="sultan2", mala=30, preco=75000, estoque = 15},                                                                      
            {title = "surano", model="surano", mala=30, preco=75000, estoque = 15},                                                                       
            {title = "adder", model="adder", mala=30, preco=75000, estoque = 15},                                                                                                                                              
            {title = "banshee2", model="banshee2", mala=30, preco=75000, estoque = 15},                                                                                                                                              
            {title = "bullet", model="bullet", mala=30, preco=75000, estoque = 15},                                                                                                                                              
            {title = "cheetah", model="cheetah", mala=30, preco=75000, estoque = 15},                                                                                                                                              
            {title = "cyclone", model="cyclone", mala=30, preco=75000, estoque = 15},                                                                                                                                              
            {title = "entity2", model="entity2", mala=30, preco=75000, estoque = 15},                                                                                                                                              
            {title = "entityxf", model="entityxf", mala=30, preco=75000, estoque = 15},                                                                                                                                              
            {title = "furia", model="furia", mala=30, preco=75000, estoque = 15},                                                                                                                                              
            {title = "gp1", model="gp1", mala=30, preco=75000, estoque = 15},                                                                                                                                              
            {title = "italigtb", model="italigtb", mala=30, preco=75000, estoque = 15},                                                                                                                                              
            {title = "nero", model="nero", mala=30, preco=75000, estoque = 15},                                                                                                                                              
            {title = "osiris", model="osiris", mala=30, preco=75000, estoque = 15},                                                                                                                                              
            {title = "pfister811", model="pfister811", mala=30, preco=75000, estoque = 15},                                                                                                                                              
            {title = "prototipo", model="prototipo", mala=30, preco=75000, estoque = 15},                                                                                                                                              
            {title = "reaper", model="reaper", mala=30, preco=75000, estoque = 15},                                                                                                                                              
            {title = "sheava", model="sheava", mala=30, preco=75000, estoque = 15},                                                                                                                                              
            {title = "sultanrs", model="sultanrs", mala=30, preco=75000, estoque = 15},                                                                                                                                              
            {title = "t20", model="t20", mala=30, preco=75000, estoque = 15},                                                                                                                                              
            {title = "taipan", model="taipan", mala=30, preco=75000, estoque = 15},                                                                                                                                              
            {title = "tempesta", model="tempesta", mala=30, preco=75000, estoque = 15},                                                                                                                                              
            {title = "turismor", model="turismor", mala=30, preco=75000, estoque = 15},                                                                                                                                              
            {title = "tyrant", model="tyrant", mala=30, preco=75000, estoque = 15},                                                                                                                                              
            {title = "vacca", model="vacca", mala=30, preco=75000, estoque = 15},                                                                                                                                              
            {title = "vagner", model="vagner", mala=30, preco=75000, estoque = 15},                                                                                                                                              
            {title = "visione", model="visione", mala=30, preco=75000, estoque = 15},                                                                                                                                              
            {title = "xa21", model="xa21", mala=30, preco=75000, estoque = 15},                                                                                                                                              
            {title = "zentorno", model="zentorno", mala=30, preco=75000, estoque = 15},                                                                                                                                              
        }
    },  
}
function getVeiculo(modelo)
    for i, cat in pairs(Config.Veiculos) do
        for i2, carro in pairs(cat.veiculos) do 
            if carro.model == modelo then
                return carro
            end
        end
    end
end


function getVeiculos()
    local veiculos = {}
    for i, cat in pairs(Config.Veiculos) do
        for i2, carro in pairs(cat.veiculos) do 
            veiculos[carro.model] = carro
        end
    end

    return veiculos
end