Config = {}

Config.AbertoAll = true
Config.TotalGaragem = 3
Config.Veiculos = {
    {
        categoria = {title="Carros", id="carros"},
        veiculos = {                                                                 
            {title = "panto", model="panto", mala=10, preco=20000, estoque = 100},                                                                      
            {title = "asea", model="asea", mala=30, preco=30000, estoque = 100},                                                                      
            {title = "rhapsody", model="rhapsody", mala=20, preco=30000, estoque = 100},                                                                                                                                         
            {title = "prairie", model="prairie", mala=30, preco=40000, estoque = 100},                                                                                                                                                                                                              
            {title = "brioso", model="brioso", mala=20, preco=50000, estoque = 100},                                                                                                                                           
            {title = "issi2", model="issi2", mala=20, preco=80000, estoque = 100},                                                                      
            {title = "cogcabrio", model="cogcabrio", mala=30, preco=110000, estoque = 100},

            {title = "f620", model="f620", mala=25, preco=130000, estoque = 15},                                                                      
            {title = "faction2", model="faction2", mala=20, preco=130000, estoque = 15},                                                                      
            {title = "zion", model="zion", mala=30, preco=130000, estoque = 15},                                                                                                                                                                                                              
            {title = "dukes", model="dukes", mala=20, preco=130000, estoque = 15},                                                                                                                                                                                                                 
            {title = "oracle2", model="oracle2", mala=30, preco=140000, estoque = 15},                                                                      
            {title = "dominator", model="dominator", mala=25, preco=140000, estoque = 15},                                                                      
            {title = "buccaneer2", model="buccaneer2", mala=20, preco=140000, estoque = 15},                                                                                                                                           
            {title = "ellie", model="ellie", mala=20, preco=140000, estoque = 15},                                                                      
            {title = "tampa", model="tampa", mala=30, preco=140000, estoque = 15},                                                                      
            {title = "tulip", model="tulip", mala=20, preco=140000, estoque = 15},                                                                      
            {title = "jackal", model="jackal", mala=40, preco=170000, estoque = 15},                                                                      
            {title = "gauntlet", model="gauntlet", mala=25, preco=170000, estoque = 15},                                                                                                                                           
            {title = "buccaneer", model="buccaneer", mala=25, preco=170000, estoque = 15},                                                                      
            {title = "exemplar", model="exemplar", mala=30, preco=180000, estoque = 15},  
            {title = "blade", model="blade", mala=20, preco=180000, estoque = 15},                                                                      
            {title = "hustler", model="hustler", mala=0, preco=180000, estoque = 15},                                                                      
            {title = "vigero", model="vigero", mala=15, preco=190000, estoque = 15},                                                                                                                                           
            {title = "asterope", model="asterope", mala=25, preco=190000, estoque = 15},                                                                                                                                                                                                             
            {title = "ruston", model="ruston", mala=10, preco=190000, estoque = 15},
            {title = "chino2", model="chino2", mala=10, preco=220000, estoque = 15},                                                                      
            {title = "picador", model="picador", mala=60, preco=220000, estoque = 15},                                                                      
            {title = "coquette3", model="coquette3", mala=0, preco=220000, estoque = 15},                                                                      
            {title = "ratloader2", model="ratloader2", mala=75, preco=220000, estoque = 15},                                                                                                                                                                                                                 
            {title = "dominator3", model="dominator3", mala=20, preco=250000, estoque = 15},                                                                      
            {title = "futo", model="futo", mala=25, preco=250000, estoque = 15}, 
            {title = "stafford", model="stafford", mala=15, preco=250000, estoque = 15},                                                                      
            {title = "sentinel3", model="sentinel3", mala=25, preco=250000, estoque = 15},                                                                                                                                        
            {title = "fusca", model="weevil", mala=10, preco=300000, estoque = 5},
            {title = "alpha", model="alpha", mala=20, preco=320000, estoque = 10},                                                                      
            {title = "cognoscenti", model="cognoscenti", mala=40, preco=340000, estoque = 10},                                                                                                                                            
            {title = "Palio", model="fugitive", mala=10, preco=350000, estoque = 5},
            {title = "Voyage", model="blista3", mala=10, preco=350000, estoque = 5},
            {title = "revolter", model="revolter", mala=40, preco=380000, estoque = 10},                                                                      
            {title = "GOL-S", model="blista", mala=20, preco=400000, estoque = 5},
            {title = "celta", model="celta", mala=0, preco=400000, estoque = 5},
            {title = "khamelion", model="khamelion", mala=10, preco=420000, estoque = 10},                                                                      
            {title = "buffalo2", model="buffalo2", mala=20, preco=430000, estoque = 10},                                                                      
            {title = "rapidgt", model="rapidgt", mala=15, preco=450000, estoque = 10},                                                                      
            {title = "Golf", model="vwgolf", mala=20, preco=500000, estoque = 5},
            {title = "Saveiro", model="vwsava", mala=30, preco=500000, estoque = 5},
            {title = "furoregt", model="furoregt", mala=10, preco=500000, estoque = 10},                                                                      
            {title = "kuruma", model="kuruma", mala=30, preco=550000, estoque = 10},                                                                      
            {title = "elegy", model="elegy", mala=20, preco=680000, estoque = 10},                                                                      
            {title = "bullet", model="bullet", mala=10, preco=700000, estoque = 10},                                                                                                                                              
            {title = "carbonizzare", model="carbonizzare", mala=10, preco=730000, estoque = 10},                                                                      
            {title = "lynx", model="lynx", mala=20, preco=750000, estoque = 10},                                                                      
            {title = "banshee", model="banshee", mala=15, preco=750000, estoque = 10},                                                                      
            {title = "rocoto", model="rocoto", mala=50, preco=750000, estoque = 10},                                                                      
            {title = "huntley", model="huntley", mala=50, preco=750000, estoque = 10},                                                                                                                                          
            {title = "xls", model="xls", mala=60, preco=750000, estoque = 10},                                                                                                                                           
            {title = "bestiagts", model="bestiagts", mala=35, preco=750000, estoque = 10},                                                                      
            {title = "raiden", model="raiden", mala=40, preco=750000, estoque = 10},                                                                      
            {title = "surano", model="surano", mala=10, preco=790000, estoque = 10},                                                                       
            {title = "civic 2010", model="civic2010", mala=10, preco=800000, estoque = 5},
            {title = "ninef", model="ninef", mala=10, preco=820000, estoque = 10},                                                                                                                                         
            {title = "cyclone", model="cyclone", mala=0, preco=840000, estoque = 10},                                                                                                                                              
            {title = "seven70", model="seven70", mala=10, preco=850000, estoque = 10},                                                                      
            {title = "flashgt", model="flashgt", mala=15, preco=880000, estoque = 10},                                                                      
            {title = "coquette", model="coquette", mala=10, preco=930000, estoque = 10},                                                                      
            {title = "elegy2", model="elegy2", mala=10, preco=930000, estoque = 10},                                                                      
            {title = "italigtb", model="italigtb", mala=0, preco=980000, estoque = 10},                                                                                                                                              
            {title = "mesa3", model="mesa3", mala=60, preco=1000000, estoque = 10},                                                                      
            {title = "baller4", model="baller4", mala=70, preco=1000000, estoque = 10},                                                                                                                                           
            {title = "dubsta2", model="dubsta2", mala=70, preco=1000000, estoque = 10},                                                                                                                                           
            {title = "banshee2", model="banshee2", mala=15, preco=1000000, estoque = 10},                                                                                                                                              
            {title = "vacca", model="vacca", mala=10, preco=1000000, estoque = 10},                                                                                                                                              
            {title = "Plymouth GTX", model="71gtx", mala=20, preco=1000000, estoque = 5},
            {title = "visione", model="visione", mala=0, preco=1000000, estoque = 10},                                                                                                                                              
            {title = "Mustang Mach 1", model="mustangmach1", mala=0, preco=1000000, estoque = 5},
            {title = "massacro", model="massacro", mala=10, preco=1030000, estoque = 10},                                                                      
            {title = "jester", model="jester", mala=10, preco=1050000, estoque = 10},                                                                      
            {title = "sultanrs", model="sultanrs", mala=25, preco=1130000, estoque = 10},                                                                                                                                              
            {title = "comet2", model="comet2", mala=20, preco=1150000, estoque = 10},                                                                      
            {title = "neon", model="neon", mala=25, preco=1170000, estoque = 10},                                                                      
            {title = "taipan", model="taipan", mala=10, preco=1180000, estoque = 10},                                                                                                                                              
            {title = "civic 2016", model="civic2016", mala=20, preco=1200000, estoque = 5},
            {title = "tempesta", model="tempesta", mala=10, preco=1230000, estoque = 10},                                                                                                                                              
            {title = "patriot", model="patriot", mala=60, preco=1250000, estoque = 10},                                                                      
            {title = "toros", model="toros", mala=50, preco=1250000, estoque = 10},   
            {title = "reaper", model="reaper", mala=15, preco=1250000, estoque = 10},                                                                                                                                              
            {title = "turismor", model="turismor", mala=0, preco=1250000, estoque = 10},                                                                                                                                              
            {title = "specter", model="specter", mala=10, preco=1250000, estoque = 10},                                                                                                                                       
            {title = "tyrant", model="tyrant", mala=10, preco=1350000, estoque = 5},                                                                                                                                              
            {title = "pariah", model="pariah", mala=20, preco=1380000, estoque = 5},                                                                      
            {title = "deveste", model="deveste", mala=0, preco=1430000, estoque = 5},                                                                      
            {title = "cheetah", model="cheetah", mala=0, preco=1440000, estoque = 5},                                                                                                                                              
            {title = "sheava", model="sheava", mala=15, preco=1450000, estoque = 5},                                                                                                                                              
            {title = "xa21", model="xa21", mala=15, preco=1500000, estoque = 5},                                                                                                                                              
            {title = "guardian", model="guardian", mala=100, preco=1500000, estoque = 5},                                                                                                                                              
            {title = "entityxf", model="entityxf", mala=0, preco=1500000, estoque = 5},                                                                                                                                              
            {title = "gp1", model="gp1", mala=10, preco=1500000, estoque = 5},                                                                                                                                              
            {title = "entity2", model="entity2", mala=10, preco=1500000, estoque = 5},                                                                                                                                              
            {title = "nero", model="nero", mala=15, preco=1500000, estoque = 5},                                                                                                                                              
            {title = "prototipo", model="prototipo", mala=0, preco=1500000, estoque = 5},                                                                                                                                              
            {title = "vagner", model="vagner", mala=0, preco=1500000, estoque = 5},                                                                                                                                              
            {title = "patriot2", model="patriot2", mala=60, preco=1500000, estoque = 5},                                                                                                                                              
            {title = "t20", model="t20", mala=10, preco=1500000, estoque = 5},                                                                                                                                              
            {title = "adder", model="adder", mala=10, preco=1500000, estoque = 5},                                                                                                                                              
            {title = "pfister811", model="pfister811", mala=10, preco=1500000, estoque = 5},                                                                                                                                              
            {title = "italigto", model="italigto", mala=15, preco=1500000, estoque = 5},                                                                      
            {title = "zentorno", model="zentorno", mala=15, preco=1500000, estoque = 5},                                                                                                                                              
            {title = "osiris", model="osiris", mala=10, preco=1500000, estoque = 5},
            {title = "focus RS", model="focusrs", mala=10, preco=1800000, estoque = 5},
            {title = "Mitsubishi Eclipse", model="eclipse", mala=0, preco=1800000, estoque = 5},
            {title = "Mercedes AMG A45", model="mercedesa45", mala=20, preco=2000000, estoque = 5},
            {title = "Nissan 370Z", model="nissan370z", mala=0, preco=2000000, estoque = 5},
            {title = "Porsche 930", model="porsche930", mala=10, preco=2000000, estoque = 5},
            {title = "Dodge Charger", model="defiant", mala=20, preco=2200000, estoque = 5},
            {title = "amarok", model="amarok", mala=80, preco=2500000, estoque = 5},
            {title = "Porsche Panamera", model="palameila", mala=30, preco=2500000, estoque = 5},
            {title = "Audi RS6", model="audirs6", mala=40, preco=2500000, estoque = 5},
            {title = "Mercedes AMG C63-S", model="rmodamgc63", mala=20, preco=2500000, estoque = 5},
            {title = "Camaro ZL1", model="2018zl1", mala=10, preco=2500000, estoque = 5},
            {title = "Tesla Prior", model="teslaprior", mala=30, preco=2500000, estoque = 5},
            {title = "Aston Martin DB11", model="db11", mala=10, preco=2500000, estoque = 5},
            {title = "Toyota Supra", model="toyotasupra", mala=0, preco=2500000, estoque = 5},
            {title = "Civic Type R", model="hondafk8", mala=30, preco=2700000, estoque = 5},
            {title = "Ford Mustang", model="fordmustang", mala=10, preco=2800000, estoque = 5},
            {title = "Audi RS7", model="audirs7", mala=40, preco=3000000, estoque = 5},
            {title = "Jaguar F-type", model="19ftype", mala=20, preco=3000000, estoque = 5},
            {title = "Nissan 180SX", model="180sx", mala=20, preco=3200000, estoque = 5},
            {title = "Mazda RX7", model="mazdarx7", mala=10, preco=3400000, estoque = 5},
            {title = "Nissan GTR", model="nissangtr", mala=10, preco=3500000, estoque = 5},
            {title = "Ford Raptor", model="raptor2017", mala=80, preco=3500000, estoque = 5},
            {title = "Lancer Evolution 9", model="lancerevolution9", mala=20, preco=3700000, estoque = 5},
            {title = "Ford GT", model="gt17", mala=0, preco=4500000, estoque = 5},
            {title = "Porsche 911R", model="911r", mala=0, preco=5000000, estoque = 5},
            {title = "Ferrari California", model="fc15", mala=20, preco=5000000, estoque = 5},
        }
    }, 
	    {
        categoria = {title="Motos", id="motos"},
        veiculos = {
            {title = "faggio", model = "faggio", mala = 0, preco = 20000, estoque = 100},
            {title = "biz25", model = "biz25", mala = 15, preco = 30000, estoque = 20},
			{title = "pcj", model = "pcj", mala = 10, preco = 40000, estoque = 100},
            {title = "150", model = "150", mala = 10, preco = 50000, estoque = 20},
			{title = "ruffian", model = "ruffian", mala = 10, preco = 70000, estoque = 100},
			{title = "vader", model = "vader", mala = 10, preco = 90000, estoque = 100},
			{title = "nemesis", model = "nemesis", mala = 10, preco = 110000, estoque = 100},

			{title = "lectro", model = "lectro", mala = 10, preco = 130000, estoque = 15},
            {title = "bros60", model = "bros60", mala = 0, preco = 150000, estoque = 10},
			{title = "defiler", model = "defiler", mala = 0, preco = 200000, estoque = 15},
			{title = "vortex", model = "vortex", mala = 05, preco = 220000, estoque = 15},
			{title = "ratbike", model = "ratbike", mala = 15, preco = 240000, estoque = 15},
			{title = "diablous", model = "diablous", mala = 05, preco = 320000, estoque = 15},
			{title = "enduro", model = "enduro", mala = 05, preco = 360000, estoque = 15},
			{title = "esskey", model = "esskey", mala = 05, preco = 360000, estoque = 15},
			{title = "cliffhanger", model = "cliffhanger", mala = 0, preco = 420000, estoque = 10},
			{title = "nightblade", model = "nightblade", mala = 05, preco = 480000, estoque = 10},
			{title = "diablous2", model = "diablous2", mala = 10, preco = 500000, estoque = 10},
			{title = "hakuchou", model = "hakuchou", mala = 10, preco = 520000, estoque = 10},
			{title = "zombiea", model = "zombiea", mala = 0, preco = 540000, estoque = 10},
			{title = "carbonrs", model = "carbonrs", mala = 10, preco = 540000, estoque = 10},
			{title = "manchez", model = "manchez", mala = 0, preco = 560000, estoque = 10},
			{title = "double", model = "double", mala = 10, preco = 560000, estoque = 10},
			{title = "gargoyle", model = "gargoyle", mala = 05, preco = 600000, estoque = 10},
            {title = "xt66", model = "xt66", mala = 0, preco = 600000, estoque = 10},
			{title = "daemon", model = "daemon", mala = 10, preco = 620000, estoque = 10},
			{title = "sanchez2", model = "sanchez2", mala = 0, preco = 660000, estoque = 10},
			{title = "sanchez", model = "sanchez", mala = 05, preco = 700000, estoque = 10},
			{title = "chimera", model = "chimera", mala = 05, preco = 700000, estoque = 10},
			{title = "bf400", model = "bf400", mala = 05, preco = 800000, estoque = 5},
			{title = "bati", model = "bati", mala = 10, preco = 800000, estoque = 5},
			{title = "bati2", model = "bati2", mala = 10, preco = 900000, estoque = 5},
			{title = "akuma", model = "akuma", mala = 10, preco = 940000, estoque = 5},
			{title = "hakuchou2", model = "hakuchou2", mala = 05, preco = 1000000, estoque = 5},
            {title = "cbrr", model = "cbrr", mala = 0, preco = 1500000, estoque = 10},
            {title = "hornet", model = "hornet", mala = 0, preco = 1600000, estoque = 10},
            {title = "r6", model = "r6", mala = 0, preco = 1700000, estoque = 10},
            {title = "z1000", model = "z1000", mala = 0, preco = 2000000, estoque = 10},
            {title = "dm1200", model = "dm1200", mala = 0, preco = 2500000, estoque = 10},
        }
    },
}
function getVeiculo(modelo)
    for i, cat in pairs(Config.Veiculos) do
        for i2, carro in pairs(cat.veiculos) do 
            if carro.model == modelo then
                return carro
            end
        end
    end
end


function getVeiculos()
    local veiculos = {}
    for i, cat in pairs(Config.Veiculos) do
        for i2, carro in pairs(cat.veiculos) do 
            veiculos[carro.model] = carro
        end
    end

    return veiculos
end