TokoVoipConfig = {
	channels = {
	    { name = "Freq. 1", subscribers = {} }, -- 1 
		{ name = "Freq. 2", subscribers = {} }, -- 2 
		{ name = "Freq. 3", subscribers = {} }, -- 3 
		{ name = "Freq. 4", subscribers = {} }, -- 4 
		{ name = "Freq. 5", subscribers = {} }, -- 5 
		{ name = "Freq. 6", subscribers = {} }, -- 6 
		{ name = "Freq. 7", subscribers = {} }, -- 7 
		{ name = "Freq. 8", subscribers = {} }, -- 8 
		{ name = "Freq. 9", subscribers = {} }, -- 9 
		{ name = "Freq. 10", subscribers = {} }, -- 10 
		{ name = "Freq. 11", subscribers = {} }, -- 11 
		{ name = "Freq. 12", subscribers = {} }, -- 12 
		{ name = "Freq. 13", subscribers = {} }, -- 13 
		{ name = "Freq. 14", subscribers = {} }, -- 14 
		{ name = "Freq. 15", subscribers = {} }, -- 15 
		{ name = "Freq. 16", subscribers = {} }, -- 16 
		{ name = "Freq. 17", subscribers = {} }, -- 17 
		{ name = "Freq. 18", subscribers = {} }, -- 18 
		{ name = "Freq. 19", subscribers = {} }, -- 19 
		{ name = "Freq. 20", subscribers = {} }, -- 20 
		{ name = "Freq. 21", subscribers = {} }, -- 21 
		{ name = "Freq. 22", subscribers = {} }, -- 22 
		{ name = "Freq. 23", subscribers = {} }, -- 23 
		{ name = "Freq. 24", subscribers = {} }, -- 24 
		{ name = "Freq. 25", subscribers = {} }, -- 25 
		{ name = "Freq. 26", subscribers = {} }, -- 26 
		{ name = "Freq. 27", subscribers = {} }, -- 27 
		{ name = "Freq. 28", subscribers = {} }, -- 28 
		{ name = "Freq. 29", subscribers = {} }, -- 29 
		{ name = "Freq. 30", subscribers = {} }, -- 30 
		{ name = "Freq. 31", subscribers = {} }, -- 31 
		{ name = "Freq. 32", subscribers = {} }, -- 32 
		{ name = "Freq. 33", subscribers = {} }, -- 33 
		{ name = "Freq. 34", subscribers = {} }, -- 34 
		{ name = "Freq. 35", subscribers = {} }, -- 35 
		{ name = "Freq. 36", subscribers = {} }, -- 36 
		{ name = "Freq. 37", subscribers = {} }, -- 37 
		{ name = "Freq. 38", subscribers = {} }, -- 38 
		{ name = "Freq. 39", subscribers = {} }, -- 39 
		{ name = "Freq. 40", subscribers = {} }, -- 40 
		{ name = "Freq. 41", subscribers = {} }, -- 41 
		{ name = "Freq. 42", subscribers = {} }, -- 42 
		{ name = "Freq. 43", subscribers = {} }, -- 43 
		{ name = "Freq. 44", subscribers = {} }, -- 44 
		{ name = "Freq. 45", subscribers = {} }, -- 45 
		{ name = "Freq. 46", subscribers = {} }, -- 46 
		{ name = "Freq. 47", subscribers = {} }, -- 47 
		{ name = "Freq. 48", subscribers = {} }, -- 48 
		{ name = "Freq. 49", subscribers = {} }, -- 49 
		{ name = "Freq. 50", subscribers = {} }, -- 50 
		{ name = "Freq. 51", subscribers = {} }, -- 51 
		{ name = "Freq. 52", subscribers = {} }, -- 52 
		{ name = "Freq. 53", subscribers = {} }, -- 53 
		{ name = "Freq. 54", subscribers = {} }, -- 54 
		{ name = "Freq. 55", subscribers = {} }, -- 55 
		{ name = "Freq. 56", subscribers = {} }, -- 56 
		{ name = "Freq. 57", subscribers = {} }, -- 57 
		{ name = "Freq. 58", subscribers = {} }, -- 58 
		{ name = "Freq. 59", subscribers = {} }, -- 59 
		{ name = "Freq. 60", subscribers = {} }, -- 60 
		{ name = "Freq. 61", subscribers = {} }, -- 61 
		{ name = "Freq. 62", subscribers = {} }, -- 62 
		{ name = "Freq. 63", subscribers = {} }, -- 63 
		{ name = "Freq. 64", subscribers = {} }, -- 64 
		{ name = "Freq. 65", subscribers = {} }, -- 65 
		{ name = "Freq. 66", subscribers = {} }, -- 66 
		{ name = "Freq. 67", subscribers = {} }, -- 67 
		{ name = "Freq. 68", subscribers = {} }, -- 68 
		{ name = "Freq. 69", subscribers = {} }, -- 69 
		{ name = "Freq. 70", subscribers = {} }, -- 70 
		{ name = "Freq. 71", subscribers = {} }, -- 71 
		{ name = "Freq. 72", subscribers = {} }, -- 72 
		{ name = "Freq. 73", subscribers = {} }, -- 73 
		{ name = "Freq. 74", subscribers = {} }, -- 74 
		{ name = "Freq. 75", subscribers = {} }, -- 75 
		{ name = "Freq. 76", subscribers = {} }, -- 76 
		{ name = "Freq. 77", subscribers = {} }, -- 77 
		{ name = "Freq. 78", subscribers = {} }, -- 78 
		{ name = "Freq. 79", subscribers = {} }, -- 79 
		{ name = "Freq. 80", subscribers = {} }, -- 80 
		{ name = "Freq. 81", subscribers = {} }, -- 81 
		{ name = "Freq. 82", subscribers = {} }, -- 82 
		{ name = "Freq. 83", subscribers = {} }, -- 83 
		{ name = "Freq. 84", subscribers = {} }, -- 84 
		{ name = "Freq. 85", subscribers = {} }, -- 85 
		{ name = "Freq. 86", subscribers = {} }, -- 86 
		{ name = "Freq. 87", subscribers = {} }, -- 87 
		{ name = "Freq. 88", subscribers = {} }, -- 88 
		{ name = "Freq. 89", subscribers = {} }, -- 89 
		{ name = "Freq. 90", subscribers = {} }, -- 90 
		{ name = "Freq. 91", subscribers = {} }, -- 91 
		{ name = "Freq. 92", subscribers = {} }, -- 92 
		{ name = "Freq. 93", subscribers = {} }, -- 93 
		{ name = "Freq. 94", subscribers = {} }, -- 94 
		{ name = "Freq. 95", subscribers = {} }, -- 95 
		{ name = "Freq. 96", subscribers = {} }, -- 96 
		{ name = "Freq. 97", subscribers = {} }, -- 97 
		{ name = "Freq. 98", subscribers = {} }, -- 98 
		{ name = "Freq. 99", subscribers = {} }, -- 99 
		{ name = "Freq. 100", subscribers = {} }, -- 100 
		{ name = "Freq. 101", subscribers = {} }, -- 101 
		{ name = "Freq. 102", subscribers = {} }, -- 102 
		{ name = "Freq. 103", subscribers = {} }, -- 103 
		{ name = "Freq. 104", subscribers = {} }, -- 104 
		{ name = "Freq. 105", subscribers = {} }, -- 105 
		{ name = "Freq. 106", subscribers = {} }, -- 106 
		{ name = "Freq. 107", subscribers = {} }, -- 107 
		{ name = "Freq. 108", subscribers = {} }, -- 108 
		{ name = "Freq. 109", subscribers = {} }, -- 109 
		{ name = "Freq. 110", subscribers = {} }, -- 110 
		{ name = "Freq. 111", subscribers = {} }, -- 111 
		{ name = "Freq. 112", subscribers = {} }, -- 112 
		{ name = "Freq. 113", subscribers = {} }, -- 113 
		{ name = "Freq. 114", subscribers = {} }, -- 114 
		{ name = "Freq. 115", subscribers = {} }, -- 115 
		{ name = "Freq. 116", subscribers = {} }, -- 116 
		{ name = "Freq. 117", subscribers = {} }, -- 117 
		{ name = "Freq. 118", subscribers = {} }, -- 118 
		{ name = "Freq. 119", subscribers = {} }, -- 119 
		{ name = "Freq. 120", subscribers = {} }, -- 120 
		{ name = "Freq. 121", subscribers = {} }, -- 121 
		{ name = "Freq. 122", subscribers = {} }, -- 122 
		{ name = "Freq. 123", subscribers = {} }, -- 123 
		{ name = "Freq. 124", subscribers = {} }, -- 124 
		{ name = "Freq. 125", subscribers = {} }, -- 125 
		{ name = "Freq. 126", subscribers = {} }, -- 126 
		{ name = "Freq. 127", subscribers = {} }, -- 127 
		{ name = "Freq. 128", subscribers = {} }, -- 128 
		{ name = "Freq. 129", subscribers = {} }, -- 129 
		{ name = "Freq. 130", subscribers = {} }, -- 130 
		{ name = "Freq. 131", subscribers = {} }, -- 131 
		{ name = "Freq. 132", subscribers = {} }, -- 132 
		{ name = "Freq. 133", subscribers = {} }, -- 133 
		{ name = "Freq. 134", subscribers = {} }, -- 134 
		{ name = "Freq. 135", subscribers = {} }, -- 135 
		{ name = "Freq. 136", subscribers = {} }, -- 136 
		{ name = "Freq. 137", subscribers = {} }, -- 137 
		{ name = "Freq. 138", subscribers = {} }, -- 138 
		{ name = "Freq. 139", subscribers = {} }, -- 139 
		{ name = "Freq. 140", subscribers = {} }, -- 140 
		{ name = "Freq. 141", subscribers = {} }, -- 141 
		{ name = "Freq. 142", subscribers = {} }, -- 142 
		{ name = "Freq. 143", subscribers = {} }, -- 143 
		{ name = "Freq. 144", subscribers = {} }, -- 144 
		{ name = "Freq. 145", subscribers = {} }, -- 145 
		{ name = "Freq. 146", subscribers = {} }, -- 146 
		{ name = "Freq. 147", subscribers = {} }, -- 147 
		{ name = "Freq. 148", subscribers = {} }, -- 148 
		{ name = "Freq. 149", subscribers = {} }, -- 149 
		{ name = "Freq. 150", subscribers = {} }, -- 150 
		{ name = "Freq. 151", subscribers = {} }, -- 151 
		{ name = "Freq. 152", subscribers = {} }, -- 152 
		{ name = "Freq. 153", subscribers = {} }, -- 153 
		{ name = "Freq. 154", subscribers = {} }, -- 154 
		{ name = "Freq. 155", subscribers = {} }, -- 155 
		{ name = "Freq. 156", subscribers = {} }, -- 156 
		{ name = "Freq. 157", subscribers = {} }, -- 157 
		{ name = "Freq. 158", subscribers = {} }, -- 158 
		{ name = "Freq. 159", subscribers = {} }, -- 159 
		{ name = "Freq. 160", subscribers = {} }, -- 160 
		{ name = "Freq. 161", subscribers = {} }, -- 161 
		{ name = "Freq. 162", subscribers = {} }, -- 162 
		{ name = "Freq. 163", subscribers = {} }, -- 163 
		{ name = "Freq. 164", subscribers = {} }, -- 164 
		{ name = "Freq. 165", subscribers = {} }, -- 165 
		{ name = "Freq. 166", subscribers = {} }, -- 166 
		{ name = "Freq. 167", subscribers = {} }, -- 167 
		{ name = "Freq. 168", subscribers = {} }, -- 168 
		{ name = "Freq. 169", subscribers = {} }, -- 169 
		{ name = "Freq. 170", subscribers = {} }, -- 170 
		{ name = "Freq. 171", subscribers = {} }, -- 171 
		{ name = "Freq. 172", subscribers = {} }, -- 172 
		{ name = "Freq. 173", subscribers = {} }, -- 173 
		{ name = "Freq. 174", subscribers = {} }, -- 174 
		{ name = "Freq. 175", subscribers = {} }, -- 175 
		{ name = "Freq. 176", subscribers = {} }, -- 176 
		{ name = "Freq. 177", subscribers = {} }, -- 177 
		{ name = "Freq. 178", subscribers = {} }, -- 178 
		{ name = "Freq. 179", subscribers = {} }, -- 179 
		{ name = "Freq. 180", subscribers = {} }, -- 180 
		{ name = "Freq. 181", subscribers = {} }, -- 181 
		{ name = "Freq. 182", subscribers = {} }, -- 182 
		{ name = "Freq. 183", subscribers = {} }, -- 183 
		{ name = "Freq. 184", subscribers = {} }, -- 184 
		{ name = "Freq. 185", subscribers = {} }, -- 185 
		{ name = "Freq. 186", subscribers = {} }, -- 186 
		{ name = "Freq. 187", subscribers = {} }, -- 187 
		{ name = "Freq. 188", subscribers = {} }, -- 188 
		{ name = "Freq. 189", subscribers = {} }, -- 189 
		{ name = "Freq. 190", subscribers = {} }, -- 190 
		{ name = "Freq. 191", subscribers = {} }, -- 191 
		{ name = "Freq. 192", subscribers = {} }, -- 192 
		{ name = "Freq. 193", subscribers = {} }, -- 193 
		{ name = "Freq. 194", subscribers = {} }, -- 194 
		{ name = "Freq. 195", subscribers = {} }, -- 195 
		{ name = "Freq. 196", subscribers = {} }, -- 196 
		{ name = "Freq. 197", subscribers = {} }, -- 197 
		{ name = "Freq. 198", subscribers = {} }, -- 198 
		{ name = "Freq. 199", subscribers = {} }, -- 199 
		{ name = "Freq. 200", subscribers = {} }, -- 200 
		{ name = "Freq. 201", subscribers = {} }, -- 201 
		{ name = "Freq. 202", subscribers = {} }, -- 202 
		{ name = "Freq. 203", subscribers = {} }, -- 203 
		{ name = "Freq. 204", subscribers = {} }, -- 204 
		{ name = "Freq. 205", subscribers = {} }, -- 205 
		{ name = "Freq. 206", subscribers = {} }, -- 206 
		{ name = "Freq. 207", subscribers = {} }, -- 207 
		{ name = "Freq. 208", subscribers = {} }, -- 208 
		{ name = "Freq. 209", subscribers = {} }, -- 209 
		{ name = "Freq. 210", subscribers = {} }, -- 210 
		{ name = "Freq. 211", subscribers = {} }, -- 211 
		{ name = "Freq. 212", subscribers = {} }, -- 212 
		{ name = "Freq. 213", subscribers = {} }, -- 213 
		{ name = "Freq. 214", subscribers = {} }, -- 214 
		{ name = "Freq. 215", subscribers = {} }, -- 215 
		{ name = "Freq. 216", subscribers = {} }, -- 216 
		{ name = "Freq. 217", subscribers = {} }, -- 217 
		{ name = "Freq. 218", subscribers = {} }, -- 218 
		{ name = "Freq. 219", subscribers = {} }, -- 219 
		{ name = "Freq. 220", subscribers = {} }, -- 220 
		{ name = "Freq. 221", subscribers = {} }, -- 221 
		{ name = "Freq. 222", subscribers = {} }, -- 222 
		{ name = "Freq. 223", subscribers = {} }, -- 223 
		{ name = "Freq. 224", subscribers = {} }, -- 224 
		{ name = "Freq. 225", subscribers = {} }, -- 225 
		{ name = "Freq. 226", subscribers = {} }, -- 226 
		{ name = "Freq. 227", subscribers = {} }, -- 227 
		{ name = "Freq. 228", subscribers = {} }, -- 228 
		{ name = "Freq. 229", subscribers = {} }, -- 229 
		{ name = "Freq. 230", subscribers = {} }, -- 230 
		{ name = "Freq. 231", subscribers = {} }, -- 231 
		{ name = "Freq. 232", subscribers = {} }, -- 232 
		{ name = "Freq. 233", subscribers = {} }, -- 233 
		{ name = "Freq. 234", subscribers = {} }, -- 234 
		{ name = "Freq. 235", subscribers = {} }, -- 235 
		{ name = "Freq. 236", subscribers = {} }, -- 236 
		{ name = "Freq. 237", subscribers = {} }, -- 237 
		{ name = "Freq. 238", subscribers = {} }, -- 238 
		{ name = "Freq. 239", subscribers = {} }, -- 239 
		{ name = "Freq. 240", subscribers = {} }, -- 240 
		{ name = "Freq. 241", subscribers = {} }, -- 241 
		{ name = "Freq. 242", subscribers = {} }, -- 242 
		{ name = "Freq. 243", subscribers = {} }, -- 243 
		{ name = "Freq. 244", subscribers = {} }, -- 244 
		{ name = "Freq. 245", subscribers = {} }, -- 245 
		{ name = "Freq. 246", subscribers = {} }, -- 246 
		{ name = "Freq. 247", subscribers = {} }, -- 247 
		{ name = "Freq. 248", subscribers = {} }, -- 248 
		{ name = "Freq. 249", subscribers = {} }, -- 249 
		{ name = "Freq. 250", subscribers = {} }, -- 250 
		{ name = "Freq. 251", subscribers = {} }, -- 251 
		{ name = "Freq. 252", subscribers = {} }, -- 252 
		{ name = "Freq. 253", subscribers = {} }, -- 253 
		{ name = "Freq. 254", subscribers = {} }, -- 254 
		{ name = "Freq. 255", subscribers = {} }, -- 255 
		{ name = "Freq. 256", subscribers = {} }, -- 256 
		{ name = "Freq. 257", subscribers = {} }, -- 257 
		{ name = "Freq. 258", subscribers = {} }, -- 258 
		{ name = "Freq. 259", subscribers = {} }, -- 259 
		{ name = "Freq. 260", subscribers = {} }, -- 260 
		{ name = "Freq. 261", subscribers = {} }, -- 261 
		{ name = "Freq. 262", subscribers = {} }, -- 262 
		{ name = "Freq. 263", subscribers = {} }, -- 263 
		{ name = "Freq. 264", subscribers = {} }, -- 264 
		{ name = "Freq. 265", subscribers = {} }, -- 265 
		{ name = "Freq. 266", subscribers = {} }, -- 266 
		{ name = "Freq. 267", subscribers = {} }, -- 267 
		{ name = "Freq. 268", subscribers = {} }, -- 268 
		{ name = "Freq. 269", subscribers = {} }, -- 269 
		{ name = "Freq. 270", subscribers = {} }, -- 270 
		{ name = "Freq. 271", subscribers = {} }, -- 271 
		{ name = "Freq. 272", subscribers = {} }, -- 272 
		{ name = "Freq. 273", subscribers = {} }, -- 273 
		{ name = "Freq. 274", subscribers = {} }, -- 274 
		{ name = "Freq. 275", subscribers = {} }, -- 275 
		{ name = "Freq. 276", subscribers = {} }, -- 276 
		{ name = "Freq. 277", subscribers = {} }, -- 277 
		{ name = "Freq. 278", subscribers = {} }, -- 278 
		{ name = "Freq. 279", subscribers = {} }, -- 279 
		{ name = "Freq. 280", subscribers = {} }, -- 280 
		{ name = "Freq. 281", subscribers = {} }, -- 281 
		{ name = "Freq. 282", subscribers = {} }, -- 282 
		{ name = "Freq. 283", subscribers = {} }, -- 283 
		{ name = "Freq. 284", subscribers = {} }, -- 284 
		{ name = "Freq. 285", subscribers = {} }, -- 285 
		{ name = "Freq. 286", subscribers = {} }, -- 286 
		{ name = "Freq. 287", subscribers = {} }, -- 287 
		{ name = "Freq. 288", subscribers = {} }, -- 288 
		{ name = "Freq. 289", subscribers = {} }, -- 289 
		{ name = "Freq. 290", subscribers = {} }, -- 290 
		{ name = "Freq. 291", subscribers = {} }, -- 291 
		{ name = "Freq. 292", subscribers = {} }, -- 292 
		{ name = "Freq. 293", subscribers = {} }, -- 293 
		{ name = "Freq. 294", subscribers = {} }, -- 294 
		{ name = "Freq. 295", subscribers = {} }, -- 295 
		{ name = "Freq. 296", subscribers = {} }, -- 296 
		{ name = "Freq. 297", subscribers = {} }, -- 297 
		{ name = "Freq. 298", subscribers = {} }, -- 298 
		{ name = "Freq. 299", subscribers = {} }, -- 299 
		{ name = "Freq. 300", subscribers = {} }, -- 300 
		{ name = "Freq. 301", subscribers = {} }, -- 301 
		{ name = "Freq. 302", subscribers = {} }, -- 302 
		{ name = "Freq. 303", subscribers = {} }, -- 303 
		{ name = "Freq. 304", subscribers = {} }, -- 304 
		{ name = "Freq. 305", subscribers = {} }, -- 305 
		{ name = "Freq. 306", subscribers = {} }, -- 306 
		{ name = "Freq. 307", subscribers = {} }, -- 307 
		{ name = "Freq. 308", subscribers = {} }, -- 308 
		{ name = "Freq. 309", subscribers = {} }, -- 309 
		{ name = "Freq. 310", subscribers = {} }, -- 310 
		{ name = "Freq. 311", subscribers = {} }, -- 311 
		{ name = "Freq. 312", subscribers = {} }, -- 312 
		{ name = "Freq. 313", subscribers = {} }, -- 313 
		{ name = "Freq. 314", subscribers = {} }, -- 314 
		{ name = "Freq. 315", subscribers = {} }, -- 315 
		{ name = "Freq. 316", subscribers = {} }, -- 316 
		{ name = "Freq. 317", subscribers = {} }, -- 317 
		{ name = "Freq. 318", subscribers = {} }, -- 318 
		{ name = "Freq. 319", subscribers = {} }, -- 319 
		{ name = "Freq. 320", subscribers = {} }, -- 320 
		{ name = "Freq. 321", subscribers = {} }, -- 321 
		{ name = "Freq. 322", subscribers = {} }, -- 322 
		{ name = "Freq. 323", subscribers = {} }, -- 323 
		{ name = "Freq. 324", subscribers = {} }, -- 324 
		{ name = "Freq. 325", subscribers = {} }, -- 325 
		{ name = "Freq. 326", subscribers = {} }, -- 326 
		{ name = "Freq. 327", subscribers = {} }, -- 327 
		{ name = "Freq. 328", subscribers = {} }, -- 328 
		{ name = "Freq. 329", subscribers = {} }, -- 329 
		{ name = "Freq. 330", subscribers = {} }, -- 330 
		{ name = "Freq. 331", subscribers = {} }, -- 331 
		{ name = "Freq. 332", subscribers = {} }, -- 332 
		{ name = "Freq. 333", subscribers = {} }, -- 333 
		{ name = "Freq. 334", subscribers = {} }, -- 334 
		{ name = "Freq. 335", subscribers = {} }, -- 335 
		{ name = "Freq. 336", subscribers = {} }, -- 336 
		{ name = "Freq. 337", subscribers = {} }, -- 337 
		{ name = "Freq. 338", subscribers = {} }, -- 338 
		{ name = "Freq. 339", subscribers = {} }, -- 339 
		{ name = "Freq. 340", subscribers = {} }, -- 340 
		{ name = "Freq. 341", subscribers = {} }, -- 341 
		{ name = "Freq. 342", subscribers = {} }, -- 342 
		{ name = "Freq. 343", subscribers = {} }, -- 343 
		{ name = "Freq. 344", subscribers = {} }, -- 344 
		{ name = "Freq. 345", subscribers = {} }, -- 345 
		{ name = "Freq. 346", subscribers = {} }, -- 346 
		{ name = "Freq. 347", subscribers = {} }, -- 347 
		{ name = "Freq. 348", subscribers = {} }, -- 348 
		{ name = "Freq. 349", subscribers = {} }, -- 349 
		{ name = "Freq. 350", subscribers = {} }, -- 350 
		{ name = "Freq. 351", subscribers = {} }, -- 351 
		{ name = "Freq. 352", subscribers = {} }, -- 352 
		{ name = "Freq. 353", subscribers = {} }, -- 353 
		{ name = "Freq. 354", subscribers = {} }, -- 354 
		{ name = "Freq. 355", subscribers = {} }, -- 355 
		{ name = "Freq. 356", subscribers = {} }, -- 356 
		{ name = "Freq. 357", subscribers = {} }, -- 357 
		{ name = "Freq. 358", subscribers = {} }, -- 358 
		{ name = "Freq. 359", subscribers = {} }, -- 359 
		{ name = "Freq. 360", subscribers = {} }, -- 360 
		{ name = "Freq. 361", subscribers = {} }, -- 361 
		{ name = "Freq. 362", subscribers = {} }, -- 362 
		{ name = "Freq. 363", subscribers = {} }, -- 363 
		{ name = "Freq. 364", subscribers = {} }, -- 364 
		{ name = "Freq. 365", subscribers = {} }, -- 365 
		{ name = "Freq. 366", subscribers = {} }, -- 366 
		{ name = "Freq. 367", subscribers = {} }, -- 367 
		{ name = "Freq. 368", subscribers = {} }, -- 368 
		{ name = "Freq. 369", subscribers = {} }, -- 369 
		{ name = "Freq. 370", subscribers = {} }, -- 370 
		{ name = "Freq. 371", subscribers = {} }, -- 371 
		{ name = "Freq. 372", subscribers = {} }, -- 372 
		{ name = "Freq. 373", subscribers = {} }, -- 373 
		{ name = "Freq. 374", subscribers = {} }, -- 374 
		{ name = "Freq. 375", subscribers = {} }, -- 375 
		{ name = "Freq. 376", subscribers = {} }, -- 376 
		{ name = "Freq. 377", subscribers = {} }, -- 377 
		{ name = "Freq. 378", subscribers = {} }, -- 378 
		{ name = "Freq. 379", subscribers = {} }, -- 379 
		{ name = "Freq. 380", subscribers = {} }, -- 380 
		{ name = "Freq. 381", subscribers = {} }, -- 381 
		{ name = "Freq. 382", subscribers = {} }, -- 382 
		{ name = "Freq. 383", subscribers = {} }, -- 383 
		{ name = "Freq. 384", subscribers = {} }, -- 384 
		{ name = "Freq. 385", subscribers = {} }, -- 385 
		{ name = "Freq. 386", subscribers = {} }, -- 386 
		{ name = "Freq. 387", subscribers = {} }, -- 387 
		{ name = "Freq. 388", subscribers = {} }, -- 388 
		{ name = "Freq. 389", subscribers = {} }, -- 389 
		{ name = "Freq. 390", subscribers = {} }, -- 390 
		{ name = "Freq. 391", subscribers = {} }, -- 391 
		{ name = "Freq. 392", subscribers = {} }, -- 392 
		{ name = "Freq. 393", subscribers = {} }, -- 393 
		{ name = "Freq. 394", subscribers = {} }, -- 394 
		{ name = "Freq. 395", subscribers = {} }, -- 395 
		{ name = "Freq. 396", subscribers = {} }, -- 396 
		{ name = "Freq. 397", subscribers = {} }, -- 397 
		{ name = "Freq. 398", subscribers = {} }, -- 398 
		{ name = "Freq. 399", subscribers = {} }, -- 399 
		{ name = "Freq. 400", subscribers = {} }, -- 400 
		{ name = "Freq. 401", subscribers = {} }, -- 401 
		{ name = "Freq. 402", subscribers = {} }, -- 402 
		{ name = "Freq. 403", subscribers = {} }, -- 403 
		{ name = "Freq. 404", subscribers = {} }, -- 404 
		{ name = "Freq. 405", subscribers = {} }, -- 405 
		{ name = "Freq. 406", subscribers = {} }, -- 406 
		{ name = "Freq. 407", subscribers = {} }, -- 407 
		{ name = "Freq. 408", subscribers = {} }, -- 408 
		{ name = "Freq. 409", subscribers = {} }, -- 409 
		{ name = "Freq. 410", subscribers = {} }, -- 410 
		{ name = "Freq. 411", subscribers = {} }, -- 411 
		{ name = "Freq. 412", subscribers = {} }, -- 412 
		{ name = "Freq. 413", subscribers = {} }, -- 413 
		{ name = "Freq. 414", subscribers = {} }, -- 414 
		{ name = "Freq. 415", subscribers = {} }, -- 415 
		{ name = "Freq. 416", subscribers = {} }, -- 416 
		{ name = "Freq. 417", subscribers = {} }, -- 417 
		{ name = "Freq. 418", subscribers = {} }, -- 418 
		{ name = "Freq. 419", subscribers = {} }, -- 419 
		{ name = "Freq. 420", subscribers = {} }, -- 420 
		{ name = "Freq. 421", subscribers = {} }, -- 421 
		{ name = "Freq. 422", subscribers = {} }, -- 422 
		{ name = "Freq. 423", subscribers = {} }, -- 423 
		{ name = "Freq. 424", subscribers = {} }, -- 424 
		{ name = "Freq. 425", subscribers = {} }, -- 425 
		{ name = "Freq. 426", subscribers = {} }, -- 426 
		{ name = "Freq. 427", subscribers = {} }, -- 427 
		{ name = "Freq. 428", subscribers = {} }, -- 428 
		{ name = "Freq. 429", subscribers = {} }, -- 429 
		{ name = "Freq. 430", subscribers = {} }, -- 430 
		{ name = "Freq. 431", subscribers = {} }, -- 431 
		{ name = "Freq. 432", subscribers = {} }, -- 432 
		{ name = "Freq. 433", subscribers = {} }, -- 433 
		{ name = "Freq. 434", subscribers = {} }, -- 434 
		{ name = "Freq. 435", subscribers = {} }, -- 435 
		{ name = "Freq. 436", subscribers = {} }, -- 436 
		{ name = "Freq. 437", subscribers = {} }, -- 437 
		{ name = "Freq. 438", subscribers = {} }, -- 438 
		{ name = "Freq. 439", subscribers = {} }, -- 439 
		{ name = "Freq. 440", subscribers = {} }, -- 440 
		{ name = "Freq. 441", subscribers = {} }, -- 441 
		{ name = "Freq. 442", subscribers = {} }, -- 442 
		{ name = "Freq. 443", subscribers = {} }, -- 443 
		{ name = "Freq. 444", subscribers = {} }, -- 444 
		{ name = "Freq. 445", subscribers = {} }, -- 445 
		{ name = "Freq. 446", subscribers = {} }, -- 446 
		{ name = "Freq. 447", subscribers = {} }, -- 447 
		{ name = "Freq. 448", subscribers = {} }, -- 448 
		{ name = "Freq. 449", subscribers = {} }, -- 449 
		{ name = "Freq. 450", subscribers = {} }, -- 450 
		{ name = "Freq. 451", subscribers = {} }, -- 451 
		{ name = "Freq. 452", subscribers = {} }, -- 452 
		{ name = "Freq. 453", subscribers = {} }, -- 453 
		{ name = "Freq. 454", subscribers = {} }, -- 454 
		{ name = "Freq. 455", subscribers = {} }, -- 455 
		{ name = "Freq. 456", subscribers = {} }, -- 456 
		{ name = "Freq. 457", subscribers = {} }, -- 457 
		{ name = "Freq. 458", subscribers = {} }, -- 458 
		{ name = "Freq. 459", subscribers = {} }, -- 459 
		{ name = "Freq. 460", subscribers = {} }, -- 460 
		{ name = "Freq. 461", subscribers = {} }, -- 461 
		{ name = "Freq. 462", subscribers = {} }, -- 462 
		{ name = "Freq. 463", subscribers = {} }, -- 463 
		{ name = "Freq. 464", subscribers = {} }, -- 464 
		{ name = "Freq. 465", subscribers = {} }, -- 465 
		{ name = "Freq. 466", subscribers = {} }, -- 466 
		{ name = "Freq. 467", subscribers = {} }, -- 467 
		{ name = "Freq. 468", subscribers = {} }, -- 468 
		{ name = "Freq. 469", subscribers = {} }, -- 469 
		{ name = "Freq. 470", subscribers = {} }, -- 470 
		{ name = "Freq. 471", subscribers = {} }, -- 471 
		{ name = "Freq. 472", subscribers = {} }, -- 472 
		{ name = "Freq. 473", subscribers = {} }, -- 473 
		{ name = "Freq. 474", subscribers = {} }, -- 474 
		{ name = "Freq. 475", subscribers = {} }, -- 475 
		{ name = "Freq. 476", subscribers = {} }, -- 476 
		{ name = "Freq. 477", subscribers = {} }, -- 477 
		{ name = "Freq. 478", subscribers = {} }, -- 478 
		{ name = "Freq. 479", subscribers = {} }, -- 479 
		{ name = "Freq. 480", subscribers = {} }, -- 480 
		{ name = "Freq. 481", subscribers = {} }, -- 481 
		{ name = "Freq. 482", subscribers = {} }, -- 482 
		{ name = "Freq. 483", subscribers = {} }, -- 483 
		{ name = "Freq. 484", subscribers = {} }, -- 484 
		{ name = "Freq. 485", subscribers = {} }, -- 485 
		{ name = "Freq. 486", subscribers = {} }, -- 486 
		{ name = "Freq. 487", subscribers = {} }, -- 487 
		{ name = "Freq. 488", subscribers = {} }, -- 488 
		{ name = "Freq. 489", subscribers = {} }, -- 489 
		{ name = "Freq. 490", subscribers = {} }, -- 490 
		{ name = "Freq. 491", subscribers = {} }, -- 491 
		{ name = "Freq. 492", subscribers = {} }, -- 492 
		{ name = "Freq. 493", subscribers = {} }, -- 493 
		{ name = "Freq. 494", subscribers = {} }, -- 494 
		{ name = "Freq. 495", subscribers = {} }, -- 495 
		{ name = "Freq. 496", subscribers = {} }, -- 496 
		{ name = "Freq. 497", subscribers = {} }, -- 497 
		{ name = "Freq. 498", subscribers = {} }, -- 498 
		{ name = "Freq. 499", subscribers = {} }, -- 499 
		{ name = "Freq. 500", subscribers = {} }, -- 500 
		{ name = "Freq. 501", subscribers = {} }, -- 501  
		{ name = "Freq. 502", subscribers = {} }, -- 502  
		{ name = "Freq. 503", subscribers = {} }, -- 503  
		{ name = "Freq. 504", subscribers = {} }, -- 504  
		{ name = "Freq. 505", subscribers = {} }, -- 505  
		{ name = "Freq. 506", subscribers = {} }, -- 506  
		{ name = "Freq. 507", subscribers = {} }, -- 507  
		{ name = "Freq. 508", subscribers = {} }, -- 508  
		{ name = "Freq. 509", subscribers = {} }, -- 509  
		{ name = "Freq. 510", subscribers = {} }, -- 510  
		{ name = "Freq. 511", subscribers = {} }, -- 511  
		{ name = "Freq. 512", subscribers = {} }, -- 512  
		{ name = "Freq. 513", subscribers = {} }, -- 513  
		{ name = "Freq. 514", subscribers = {} }, -- 514  
		{ name = "Freq. 515", subscribers = {} }, -- 515  
		{ name = "Freq. 516", subscribers = {} }, -- 516  
		{ name = "Freq. 517", subscribers = {} }, -- 517  
		{ name = "Freq. 518", subscribers = {} }, -- 518  
		{ name = "Freq. 519", subscribers = {} }, -- 519  
		{ name = "Freq. 520", subscribers = {} }, -- 520  
		{ name = "Freq. 521", subscribers = {} }, -- 521  
		{ name = "Freq. 522", subscribers = {} }, -- 522  
		{ name = "Freq. 523", subscribers = {} }, -- 523  
		{ name = "Freq. 524", subscribers = {} }, -- 524  
		{ name = "Freq. 525", subscribers = {} }, -- 525  
		{ name = "Freq. 526", subscribers = {} }, -- 526  
		{ name = "Freq. 527", subscribers = {} }, -- 527  
		{ name = "Freq. 528", subscribers = {} }, -- 528  
		{ name = "Freq. 529", subscribers = {} }, -- 529  
		{ name = "Freq. 530", subscribers = {} }, -- 530  
		{ name = "Freq. 531", subscribers = {} }, -- 531  
		{ name = "Freq. 532", subscribers = {} }, -- 532  
		{ name = "Freq. 533", subscribers = {} }, -- 533  
		{ name = "Freq. 534", subscribers = {} }, -- 534  
		{ name = "Freq. 535", subscribers = {} }, -- 535  
		{ name = "Freq. 536", subscribers = {} }, -- 536  
		{ name = "Freq. 537", subscribers = {} }, -- 537  
		{ name = "Freq. 538", subscribers = {} }, -- 538  
		{ name = "Freq. 539", subscribers = {} }, -- 539  
		{ name = "Freq. 540", subscribers = {} }, -- 540  
		{ name = "Freq. 541", subscribers = {} }, -- 541  
		{ name = "Freq. 542", subscribers = {} }, -- 542  
		{ name = "Freq. 543", subscribers = {} }, -- 543  
		{ name = "Freq. 544", subscribers = {} }, -- 544  
		{ name = "Freq. 545", subscribers = {} }, -- 545  
		{ name = "Freq. 546", subscribers = {} }, -- 546  
		{ name = "Freq. 547", subscribers = {} }, -- 547  
		{ name = "Freq. 548", subscribers = {} }, -- 548  
		{ name = "Freq. 549", subscribers = {} }, -- 549  
		{ name = "Freq. 550", subscribers = {} }, -- 550  
		{ name = "Freq. 551", subscribers = {} }, -- 551  
		{ name = "Freq. 552", subscribers = {} }, -- 552  
		{ name = "Freq. 553", subscribers = {} }, -- 553  
		{ name = "Freq. 554", subscribers = {} }, -- 554  
		{ name = "Freq. 555", subscribers = {} }, -- 555  
		{ name = "Freq. 556", subscribers = {} }, -- 556  
		{ name = "Freq. 557", subscribers = {} }, -- 557  
		{ name = "Freq. 558", subscribers = {} }, -- 558  
		{ name = "Freq. 559", subscribers = {} }, -- 559  
		{ name = "Freq. 560", subscribers = {} }, -- 560  
		{ name = "Freq. 561", subscribers = {} }, -- 561  
		{ name = "Freq. 562", subscribers = {} }, -- 562  
		{ name = "Freq. 563", subscribers = {} }, -- 563  
		{ name = "Freq. 564", subscribers = {} }, -- 564  
		{ name = "Freq. 565", subscribers = {} }, -- 565  
		{ name = "Freq. 566", subscribers = {} }, -- 566  
		{ name = "Freq. 567", subscribers = {} }, -- 567  
		{ name = "Freq. 568", subscribers = {} }, -- 568  
		{ name = "Freq. 569", subscribers = {} }, -- 569  
		{ name = "Freq. 570", subscribers = {} }, -- 570  
		{ name = "Freq. 571", subscribers = {} }, -- 571  
		{ name = "Freq. 572", subscribers = {} }, -- 572  
		{ name = "Freq. 573", subscribers = {} }, -- 573  
		{ name = "Freq. 574", subscribers = {} }, -- 574  
		{ name = "Freq. 575", subscribers = {} }, -- 575  
		{ name = "Freq. 576", subscribers = {} }, -- 576  
		{ name = "Freq. 577", subscribers = {} }, -- 577  
		{ name = "Freq. 578", subscribers = {} }, -- 578  
		{ name = "Freq. 579", subscribers = {} }, -- 579  
		{ name = "Freq. 580", subscribers = {} }, -- 580  
		{ name = "Freq. 581", subscribers = {} }, -- 581  
		{ name = "Freq. 582", subscribers = {} }, -- 582  
		{ name = "Freq. 583", subscribers = {} }, -- 583  
		{ name = "Freq. 584", subscribers = {} }, -- 584  
		{ name = "Freq. 585", subscribers = {} }, -- 585  
		{ name = "Freq. 586", subscribers = {} }, -- 586  
		{ name = "Freq. 587", subscribers = {} }, -- 587  
		{ name = "Freq. 588", subscribers = {} }, -- 588  
		{ name = "Freq. 589", subscribers = {} }, -- 589  
		{ name = "Freq. 590", subscribers = {} }, -- 590  
		{ name = "Freq. 591", subscribers = {} }, -- 591  
		{ name = "Freq. 592", subscribers = {} }, -- 592  
		{ name = "Freq. 593", subscribers = {} }, -- 593  
		{ name = "Freq. 594", subscribers = {} }, -- 594  
		{ name = "Freq. 595", subscribers = {} }, -- 595  
		{ name = "Freq. 596", subscribers = {} }, -- 596  
		{ name = "Freq. 597", subscribers = {} }, -- 597  
		{ name = "Freq. 598", subscribers = {} }, -- 598  
		{ name = "Freq. 599", subscribers = {} }, -- 599  
		{ name = "Freq. 600", subscribers = {} }, -- 600  
		{ name = "Freq. 601", subscribers = {} }, -- 601  
		{ name = "Freq. 602", subscribers = {} }, -- 602  
		{ name = "Freq. 603", subscribers = {} }, -- 603  
		{ name = "Freq. 604", subscribers = {} }, -- 604  
		{ name = "Freq. 605", subscribers = {} }, -- 605  
		{ name = "Freq. 606", subscribers = {} }, -- 606  
		{ name = "Freq. 607", subscribers = {} }, -- 607  
		{ name = "Freq. 608", subscribers = {} }, -- 608  
		{ name = "Freq. 609", subscribers = {} }, -- 609  
		{ name = "Freq. 610", subscribers = {} }, -- 610  
		{ name = "Freq. 611", subscribers = {} }, -- 611  
		{ name = "Freq. 612", subscribers = {} }, -- 612  
		{ name = "Freq. 613", subscribers = {} }, -- 613  
		{ name = "Freq. 614", subscribers = {} }, -- 614  
		{ name = "Freq. 615", subscribers = {} }, -- 615  
		{ name = "Freq. 616", subscribers = {} }, -- 616  
		{ name = "Freq. 617", subscribers = {} }, -- 617  
		{ name = "Freq. 618", subscribers = {} }, -- 618  
		{ name = "Freq. 619", subscribers = {} }, -- 619  
		{ name = "Freq. 620", subscribers = {} }, -- 620  
		{ name = "Freq. 621", subscribers = {} }, -- 621  
		{ name = "Freq. 622", subscribers = {} }, -- 622  
		{ name = "Freq. 623", subscribers = {} }, -- 623  
		{ name = "Freq. 624", subscribers = {} }, -- 624  
		{ name = "Freq. 625", subscribers = {} }, -- 625  
		{ name = "Freq. 626", subscribers = {} }, -- 626  
		{ name = "Freq. 627", subscribers = {} }, -- 627  
		{ name = "Freq. 628", subscribers = {} }, -- 628  
		{ name = "Freq. 629", subscribers = {} }, -- 629  
		{ name = "Freq. 630", subscribers = {} }, -- 630  
		{ name = "Freq. 631", subscribers = {} }, -- 631  
		{ name = "Freq. 632", subscribers = {} }, -- 632  
		{ name = "Freq. 633", subscribers = {} }, -- 633  
		{ name = "Freq. 634", subscribers = {} }, -- 634  
		{ name = "Freq. 635", subscribers = {} }, -- 635  
		{ name = "Freq. 636", subscribers = {} }, -- 636  
		{ name = "Freq. 637", subscribers = {} }, -- 637  
		{ name = "Freq. 638", subscribers = {} }, -- 638  
		{ name = "Freq. 639", subscribers = {} }, -- 639  
		{ name = "Freq. 640", subscribers = {} }, -- 640  
		{ name = "Freq. 641", subscribers = {} }, -- 641  
		{ name = "Freq. 642", subscribers = {} }, -- 642  
		{ name = "Freq. 643", subscribers = {} }, -- 643  
		{ name = "Freq. 644", subscribers = {} }, -- 644  
		{ name = "Freq. 645", subscribers = {} }, -- 645  
		{ name = "Freq. 646", subscribers = {} }, -- 646  
		{ name = "Freq. 647", subscribers = {} }, -- 647  
		{ name = "Freq. 648", subscribers = {} }, -- 648  
		{ name = "Freq. 649", subscribers = {} }, -- 649  
		{ name = "Freq. 650", subscribers = {} }, -- 650  
		{ name = "Freq. 651", subscribers = {} }, -- 651  
		{ name = "Freq. 652", subscribers = {} }, -- 652  
		{ name = "Freq. 653", subscribers = {} }, -- 653  
		{ name = "Freq. 654", subscribers = {} }, -- 654  
		{ name = "Freq. 655", subscribers = {} }, -- 655  
		{ name = "Freq. 656", subscribers = {} }, -- 656  
		{ name = "Freq. 657", subscribers = {} }, -- 657  
		{ name = "Freq. 658", subscribers = {} }, -- 658  
		{ name = "Freq. 659", subscribers = {} }, -- 659  
		{ name = "Freq. 660", subscribers = {} }, -- 660  
		{ name = "Freq. 661", subscribers = {} }, -- 661  
		{ name = "Freq. 662", subscribers = {} }, -- 662  
		{ name = "Freq. 663", subscribers = {} }, -- 663  
		{ name = "Freq. 664", subscribers = {} }, -- 664  
		{ name = "Freq. 665", subscribers = {} }, -- 665  
		{ name = "Freq. 666", subscribers = {} }, -- 666  
		{ name = "Freq. 667", subscribers = {} }, -- 667  
		{ name = "Freq. 668", subscribers = {} }, -- 668  
		{ name = "Freq. 669", subscribers = {} }, -- 669  
		{ name = "Freq. 670", subscribers = {} }, -- 670  
		{ name = "Freq. 671", subscribers = {} }, -- 671  
		{ name = "Freq. 672", subscribers = {} }, -- 672  
		{ name = "Freq. 673", subscribers = {} }, -- 673  
		{ name = "Freq. 674", subscribers = {} }, -- 674  
		{ name = "Freq. 675", subscribers = {} }, -- 675  
		{ name = "Freq. 676", subscribers = {} }, -- 676  
		{ name = "Freq. 677", subscribers = {} }, -- 677  
		{ name = "Freq. 678", subscribers = {} }, -- 678  
		{ name = "Freq. 679", subscribers = {} }, -- 679  
		{ name = "Freq. 680", subscribers = {} }, -- 680  
		{ name = "Freq. 681", subscribers = {} }, -- 681  
		{ name = "Freq. 682", subscribers = {} }, -- 682  
		{ name = "Freq. 683", subscribers = {} }, -- 683  
		{ name = "Freq. 684", subscribers = {} }, -- 684  
		{ name = "Freq. 685", subscribers = {} }, -- 685  
		{ name = "Freq. 686", subscribers = {} }, -- 686  
		{ name = "Freq. 687", subscribers = {} }, -- 687  
		{ name = "Freq. 688", subscribers = {} }, -- 688  
		{ name = "Freq. 689", subscribers = {} }, -- 689  
		{ name = "Freq. 690", subscribers = {} }, -- 690  
		{ name = "Freq. 691", subscribers = {} }, -- 691  
		{ name = "Freq. 692", subscribers = {} }, -- 692  
		{ name = "Freq. 693", subscribers = {} }, -- 693  
		{ name = "Freq. 694", subscribers = {} }, -- 694  
		{ name = "Freq. 695", subscribers = {} }, -- 695  
		{ name = "Freq. 696", subscribers = {} }, -- 696  
		{ name = "Freq. 697", subscribers = {} }, -- 697  
		{ name = "Freq. 698", subscribers = {} }, -- 698  
		{ name = "Freq. 699", subscribers = {} }, -- 699  
		{ name = "Freq. 700", subscribers = {} }, -- 700  
		{ name = "Freq. 701", subscribers = {} }, -- 701  
		{ name = "Freq. 702", subscribers = {} }, -- 702  
		{ name = "Freq. 703", subscribers = {} }, -- 703  
		{ name = "Freq. 704", subscribers = {} }, -- 704  
		{ name = "Freq. 705", subscribers = {} }, -- 705  
		{ name = "Freq. 706", subscribers = {} }, -- 706  
		{ name = "Freq. 707", subscribers = {} }, -- 707  
		{ name = "Freq. 708", subscribers = {} }, -- 708  
		{ name = "Freq. 709", subscribers = {} }, -- 709  
		{ name = "Freq. 710", subscribers = {} }, -- 710  
		{ name = "Freq. 711", subscribers = {} }, -- 711  
		{ name = "Freq. 712", subscribers = {} }, -- 712  
		{ name = "Freq. 713", subscribers = {} }, -- 713  
		{ name = "Freq. 714", subscribers = {} }, -- 714  
		{ name = "Freq. 715", subscribers = {} }, -- 715  
		{ name = "Freq. 716", subscribers = {} }, -- 716  
		{ name = "Freq. 717", subscribers = {} }, -- 717  
		{ name = "Freq. 718", subscribers = {} }, -- 718  
		{ name = "Freq. 719", subscribers = {} }, -- 719  
		{ name = "Freq. 720", subscribers = {} }, -- 720  
		{ name = "Freq. 721", subscribers = {} }, -- 721  
		{ name = "Freq. 722", subscribers = {} }, -- 722  
		{ name = "Freq. 723", subscribers = {} }, -- 723  
		{ name = "Freq. 724", subscribers = {} }, -- 724  
		{ name = "Freq. 725", subscribers = {} }, -- 725  
		{ name = "Freq. 726", subscribers = {} }, -- 726  
		{ name = "Freq. 727", subscribers = {} }, -- 727  
		{ name = "Freq. 728", subscribers = {} }, -- 728  
		{ name = "Freq. 729", subscribers = {} }, -- 729  
		{ name = "Freq. 730", subscribers = {} }, -- 730  
		{ name = "Freq. 731", subscribers = {} }, -- 731  
		{ name = "Freq. 732", subscribers = {} }, -- 732  
		{ name = "Freq. 733", subscribers = {} }, -- 733  
		{ name = "Freq. 734", subscribers = {} }, -- 734  
		{ name = "Freq. 735", subscribers = {} }, -- 735  
		{ name = "Freq. 736", subscribers = {} }, -- 736  
		{ name = "Freq. 737", subscribers = {} }, -- 737  
		{ name = "Freq. 738", subscribers = {} }, -- 738  
		{ name = "Freq. 739", subscribers = {} }, -- 739  
		{ name = "Freq. 740", subscribers = {} }, -- 740  
		{ name = "Freq. 741", subscribers = {} }, -- 741  
		{ name = "Freq. 742", subscribers = {} }, -- 742  
		{ name = "Freq. 743", subscribers = {} }, -- 743  
		{ name = "Freq. 744", subscribers = {} }, -- 744  
		{ name = "Freq. 745", subscribers = {} }, -- 745  
		{ name = "Freq. 746", subscribers = {} }, -- 746  
		{ name = "Freq. 747", subscribers = {} }, -- 747  
		{ name = "Freq. 748", subscribers = {} }, -- 748  
		{ name = "Freq. 749", subscribers = {} }, -- 749  
		{ name = "Freq. 750", subscribers = {} }, -- 750  
		{ name = "Freq. 751", subscribers = {} }, -- 751  
		{ name = "Freq. 752", subscribers = {} }, -- 752  
		{ name = "Freq. 753", subscribers = {} }, -- 753  
		{ name = "Freq. 754", subscribers = {} }, -- 754  
		{ name = "Freq. 755", subscribers = {} }, -- 755  
		{ name = "Freq. 756", subscribers = {} }, -- 756  
		{ name = "Freq. 757", subscribers = {} }, -- 757  
		{ name = "Freq. 758", subscribers = {} }, -- 758  
		{ name = "Freq. 759", subscribers = {} }, -- 759  
		{ name = "Freq. 760", subscribers = {} }, -- 760  
		{ name = "Freq. 761", subscribers = {} }, -- 761  
		{ name = "Freq. 762", subscribers = {} }, -- 762  
		{ name = "Freq. 763", subscribers = {} }, -- 763  
		{ name = "Freq. 764", subscribers = {} }, -- 764  
		{ name = "Freq. 765", subscribers = {} }, -- 765  
		{ name = "Freq. 766", subscribers = {} }, -- 766  
		{ name = "Freq. 767", subscribers = {} }, -- 767  
		{ name = "Freq. 768", subscribers = {} }, -- 768  
		{ name = "Freq. 769", subscribers = {} }, -- 769  
		{ name = "Freq. 770", subscribers = {} }, -- 770  
		{ name = "Freq. 771", subscribers = {} }, -- 771  
		{ name = "Freq. 772", subscribers = {} }, -- 772  
		{ name = "Freq. 773", subscribers = {} }, -- 773  
		{ name = "Freq. 774", subscribers = {} }, -- 774  
		{ name = "Freq. 775", subscribers = {} }, -- 775  
		{ name = "Freq. 776", subscribers = {} }, -- 776  
		{ name = "Freq. 777", subscribers = {} }, -- 777  
		{ name = "Freq. 778", subscribers = {} }, -- 778  
		{ name = "Freq. 779", subscribers = {} }, -- 779  
		{ name = "Freq. 780", subscribers = {} }, -- 780  
		{ name = "Freq. 781", subscribers = {} }, -- 781  
		{ name = "Freq. 782", subscribers = {} }, -- 782  
		{ name = "Freq. 783", subscribers = {} }, -- 783  
		{ name = "Freq. 784", subscribers = {} }, -- 784  
		{ name = "Freq. 785", subscribers = {} }, -- 785  
		{ name = "Freq. 786", subscribers = {} }, -- 786  
		{ name = "Freq. 787", subscribers = {} }, -- 787  
		{ name = "Freq. 788", subscribers = {} }, -- 788  
		{ name = "Freq. 789", subscribers = {} }, -- 789  
		{ name = "Freq. 790", subscribers = {} }, -- 790  
		{ name = "Freq. 791", subscribers = {} }, -- 791  
		{ name = "Freq. 792", subscribers = {} }, -- 792  
		{ name = "Freq. 793", subscribers = {} }, -- 793  
		{ name = "Freq. 794", subscribers = {} }, -- 794  
		{ name = "Freq. 795", subscribers = {} }, -- 795  
		{ name = "Freq. 796", subscribers = {} }, -- 796  
		{ name = "Freq. 797", subscribers = {} }, -- 797  
		{ name = "Freq. 798", subscribers = {} }, -- 798  
		{ name = "Freq. 799", subscribers = {} }, -- 799  
		{ name = "Freq. 800", subscribers = {} }, -- 800  
		{ name = "Freq. 801", subscribers = {} }, -- 801   
		{ name = "Freq. 802", subscribers = {} }, -- 802   
		{ name = "Freq. 803", subscribers = {} }, -- 803   
		{ name = "Freq. 804", subscribers = {} }, -- 804   
		{ name = "Freq. 805", subscribers = {} }, -- 805   
		{ name = "Freq. 806", subscribers = {} }, -- 806   
		{ name = "Freq. 807", subscribers = {} }, -- 807   
		{ name = "Freq. 808", subscribers = {} }, -- 808   
		{ name = "Freq. 809", subscribers = {} }, -- 809   
		{ name = "Freq. 810", subscribers = {} }, -- 810   
		{ name = "Freq. 811", subscribers = {} }, -- 811   
		{ name = "Freq. 812", subscribers = {} }, -- 812   
		{ name = "Freq. 813", subscribers = {} }, -- 813   
		{ name = "Freq. 814", subscribers = {} }, -- 814   
		{ name = "Freq. 815", subscribers = {} }, -- 815   
		{ name = "Freq. 816", subscribers = {} }, -- 816   
		{ name = "Freq. 817", subscribers = {} }, -- 817   
		{ name = "Freq. 818", subscribers = {} }, -- 818   
		{ name = "Freq. 819", subscribers = {} }, -- 819   
		{ name = "Freq. 820", subscribers = {} }, -- 820   
		{ name = "Freq. 821", subscribers = {} }, -- 821   
		{ name = "Freq. 822", subscribers = {} }, -- 822   
		{ name = "Freq. 823", subscribers = {} }, -- 823   
		{ name = "Freq. 824", subscribers = {} }, -- 824   
		{ name = "Freq. 825", subscribers = {} }, -- 825   
		{ name = "Freq. 826", subscribers = {} }, -- 826   
		{ name = "Freq. 827", subscribers = {} }, -- 827   
		{ name = "Freq. 828", subscribers = {} }, -- 828   
		{ name = "Freq. 829", subscribers = {} }, -- 829   
		{ name = "Freq. 830", subscribers = {} }, -- 830   
		{ name = "Freq. 831", subscribers = {} }, -- 831   
		{ name = "Freq. 832", subscribers = {} }, -- 832   
		{ name = "Freq. 833", subscribers = {} }, -- 833   
		{ name = "Freq. 834", subscribers = {} }, -- 834   
		{ name = "Freq. 835", subscribers = {} }, -- 835   
		{ name = "Freq. 836", subscribers = {} }, -- 836   
		{ name = "Freq. 837", subscribers = {} }, -- 837   
		{ name = "Freq. 838", subscribers = {} }, -- 838   
		{ name = "Freq. 839", subscribers = {} }, -- 839   
		{ name = "Freq. 840", subscribers = {} }, -- 840   
		{ name = "Freq. 841", subscribers = {} }, -- 841   
		{ name = "Freq. 842", subscribers = {} }, -- 842   
		{ name = "Freq. 843", subscribers = {} }, -- 843   
		{ name = "Freq. 844", subscribers = {} }, -- 844   
		{ name = "Freq. 845", subscribers = {} }, -- 845   
		{ name = "Freq. 846", subscribers = {} }, -- 846   
		{ name = "Freq. 847", subscribers = {} }, -- 847   
		{ name = "Freq. 848", subscribers = {} }, -- 848   
		{ name = "Freq. 849", subscribers = {} }, -- 849   
		{ name = "Freq. 850", subscribers = {} }, -- 850   
		{ name = "Freq. 851", subscribers = {} }, -- 851   
		{ name = "Freq. 852", subscribers = {} }, -- 852   
		{ name = "Freq. 853", subscribers = {} }, -- 853   
		{ name = "Freq. 854", subscribers = {} }, -- 854   
		{ name = "Freq. 855", subscribers = {} }, -- 855   
		{ name = "Freq. 856", subscribers = {} }, -- 856   
		{ name = "Freq. 857", subscribers = {} }, -- 857   
		{ name = "Freq. 858", subscribers = {} }, -- 858   
		{ name = "Freq. 859", subscribers = {} }, -- 859   
		{ name = "Freq. 860", subscribers = {} }, -- 860   
		{ name = "Freq. 861", subscribers = {} }, -- 861   
		{ name = "Freq. 862", subscribers = {} }, -- 862   
		{ name = "Freq. 863", subscribers = {} }, -- 863   
		{ name = "Freq. 864", subscribers = {} }, -- 864   
		{ name = "Freq. 865", subscribers = {} }, -- 865   
		{ name = "Freq. 866", subscribers = {} }, -- 866   
		{ name = "Freq. 867", subscribers = {} }, -- 867   
		{ name = "Freq. 868", subscribers = {} }, -- 868   
		{ name = "Freq. 869", subscribers = {} }, -- 869   
		{ name = "Freq. 870", subscribers = {} }, -- 870   
		{ name = "Freq. 871", subscribers = {} }, -- 871   
		{ name = "Freq. 872", subscribers = {} }, -- 872   
		{ name = "Freq. 873", subscribers = {} }, -- 873   
		{ name = "Freq. 874", subscribers = {} }, -- 874   
		{ name = "Freq. 875", subscribers = {} }, -- 875   
		{ name = "Freq. 876", subscribers = {} }, -- 876   
		{ name = "Freq. 877", subscribers = {} }, -- 877   
		{ name = "Freq. 878", subscribers = {} }, -- 878   
		{ name = "Freq. 879", subscribers = {} }, -- 879   
		{ name = "Freq. 880", subscribers = {} }, -- 880   
		{ name = "Freq. 881", subscribers = {} }, -- 881   
		{ name = "Freq. 882", subscribers = {} }, -- 882   
		{ name = "Freq. 883", subscribers = {} }, -- 883   
		{ name = "Freq. 884", subscribers = {} }, -- 884   
		{ name = "Freq. 885", subscribers = {} }, -- 885   
		{ name = "Freq. 886", subscribers = {} }, -- 886   
		{ name = "Freq. 887", subscribers = {} }, -- 887   
		{ name = "Freq. 888", subscribers = {} }, -- 888   
		{ name = "Freq. 889", subscribers = {} }, -- 889   
		{ name = "Freq. 890", subscribers = {} }, -- 890   
		{ name = "Freq. 891", subscribers = {} }, -- 891   
		{ name = "Freq. 892", subscribers = {} }, -- 892   
		{ name = "Freq. 893", subscribers = {} }, -- 893   
		{ name = "Freq. 894", subscribers = {} }, -- 894   
		{ name = "Freq. 895", subscribers = {} }, -- 895   
		{ name = "Freq. 896", subscribers = {} }, -- 896   
		{ name = "Freq. 897", subscribers = {} }, -- 897   
		{ name = "Freq. 898", subscribers = {} }, -- 898   
		{ name = "Freq. 899", subscribers = {} }, -- 899   
		{ name = "Freq. 900", subscribers = {} }, -- 900   
		{ name = "Freq. 901", subscribers = {} }, -- 901   
		{ name = "Freq. 902", subscribers = {} }, -- 902   
		{ name = "Freq. 903", subscribers = {} }, -- 903   
		{ name = "Freq. 904", subscribers = {} }, -- 904   
		{ name = "Freq. 905", subscribers = {} }, -- 905   
		{ name = "Freq. 906", subscribers = {} }, -- 906   
		{ name = "Freq. 907", subscribers = {} }, -- 907   
		{ name = "Freq. 908", subscribers = {} }, -- 908   
		{ name = "Freq. 909", subscribers = {} }, -- 909   
		{ name = "Freq. 910", subscribers = {} }, -- 910   
		{ name = "Freq. 911", subscribers = {} }, -- 911   
		{ name = "Freq. 912", subscribers = {} }, -- 912   
		{ name = "Freq. 913", subscribers = {} }, -- 913   
		{ name = "Freq. 914", subscribers = {} }, -- 914   
		{ name = "Freq. 915", subscribers = {} }, -- 915   
		{ name = "Freq. 916", subscribers = {} }, -- 916   
		{ name = "Freq. 917", subscribers = {} }, -- 917   
		{ name = "Freq. 918", subscribers = {} }, -- 918   
		{ name = "Freq. 919", subscribers = {} }, -- 919   
		{ name = "Freq. 920", subscribers = {} }, -- 920   
		{ name = "Freq. 921", subscribers = {} }, -- 921   
		{ name = "Freq. 922", subscribers = {} }, -- 922   
		{ name = "Freq. 923", subscribers = {} }, -- 923   
		{ name = "Freq. 924", subscribers = {} }, -- 924   
		{ name = "Freq. 925", subscribers = {} }, -- 925   
		{ name = "Freq. 926", subscribers = {} }, -- 926   
		{ name = "Freq. 927", subscribers = {} }, -- 927   
		{ name = "Freq. 928", subscribers = {} }, -- 928   
		{ name = "Freq. 929", subscribers = {} }, -- 929   
		{ name = "Freq. 930", subscribers = {} }, -- 930   
		{ name = "Freq. 931", subscribers = {} }, -- 931   
		{ name = "Freq. 932", subscribers = {} }, -- 932   
		{ name = "Freq. 933", subscribers = {} }, -- 933   
		{ name = "Freq. 934", subscribers = {} }, -- 934   
		{ name = "Freq. 935", subscribers = {} }, -- 935   
		{ name = "Freq. 936", subscribers = {} }, -- 936   
		{ name = "Freq. 937", subscribers = {} }, -- 937   
		{ name = "Freq. 938", subscribers = {} }, -- 938   
		{ name = "Freq. 939", subscribers = {} }, -- 939   
		{ name = "Freq. 940", subscribers = {} }, -- 940   
		{ name = "Freq. 941", subscribers = {} }, -- 941   
		{ name = "Freq. 942", subscribers = {} }, -- 942   
		{ name = "Freq. 943", subscribers = {} }, -- 943   
		{ name = "Freq. 944", subscribers = {} }, -- 944   
		{ name = "Freq. 945", subscribers = {} }, -- 945   
		{ name = "Freq. 946", subscribers = {} }, -- 946   
		{ name = "Freq. 947", subscribers = {} }, -- 947   
		{ name = "Freq. 948", subscribers = {} }, -- 948   
		{ name = "Freq. 949", subscribers = {} }, -- 949   
		{ name = "Freq. 950", subscribers = {} }, -- 950   
		{ name = "Freq. 951", subscribers = {} }, -- 951   
		{ name = "Freq. 952", subscribers = {} }, -- 952   
		{ name = "Freq. 953", subscribers = {} }, -- 953   
		{ name = "Freq. 954", subscribers = {} }, -- 954   
		{ name = "Freq. 955", subscribers = {} }, -- 955   
		{ name = "Freq. 956", subscribers = {} }, -- 956   
		{ name = "Freq. 957", subscribers = {} }, -- 957   
		{ name = "Freq. 958", subscribers = {} }, -- 958   
		{ name = "Freq. 959", subscribers = {} }, -- 959   
		{ name = "Freq. 960", subscribers = {} }, -- 960   
		{ name = "Freq. 961", subscribers = {} }, -- 961   
		{ name = "Freq. 962", subscribers = {} }, -- 962   
		{ name = "Freq. 963", subscribers = {} }, -- 963   
		{ name = "Freq. 964", subscribers = {} }, -- 964   
		{ name = "Freq. 965", subscribers = {} }, -- 965   
		{ name = "Freq. 966", subscribers = {} }, -- 966   
		{ name = "Freq. 967", subscribers = {} }, -- 967   
		{ name = "Freq. 968", subscribers = {} }, -- 968   
		{ name = "Freq. 969", subscribers = {} }, -- 969   
		{ name = "Freq. 970", subscribers = {} }, -- 970   
		{ name = "Freq. 971", subscribers = {} }, -- 971   
		{ name = "Freq. 972", subscribers = {} }, -- 972   
		{ name = "Freq. 973", subscribers = {} }, -- 973   
		{ name = "Freq. 974", subscribers = {} }, -- 974   
		{ name = "Freq. 975", subscribers = {} }, -- 975   
		{ name = "Freq. 976", subscribers = {} }, -- 976   
		{ name = "Freq. 977", subscribers = {} }, -- 977   
		{ name = "Freq. 978", subscribers = {} }, -- 978   
		{ name = "Freq. 979", subscribers = {} }, -- 979   
		{ name = "Freq. 980", subscribers = {} }, -- 980   
		{ name = "Freq. 981", subscribers = {} }, -- 981   
		{ name = "Freq. 982", subscribers = {} }, -- 982   
		{ name = "Freq. 983", subscribers = {} }, -- 983   
		{ name = "Freq. 984", subscribers = {} }, -- 984   
		{ name = "Freq. 985", subscribers = {} }, -- 985   
		{ name = "Freq. 986", subscribers = {} }, -- 986   
		{ name = "Freq. 987", subscribers = {} }, -- 987   
		{ name = "Freq. 988", subscribers = {} }, -- 988   
		{ name = "Freq. 989", subscribers = {} }, -- 989   
		{ name = "Freq. 990", subscribers = {} }, -- 990   
		{ name = "Freq. 991", subscribers = {} }, -- 991   
		{ name = "Freq. 992", subscribers = {} }, -- 992   
		{ name = "Freq. 993", subscribers = {} }, -- 993   
		{ name = "Freq. 994", subscribers = {} }, -- 994   
		{ name = "Freq. 995", subscribers = {} }, -- 995   
		{ name = "Freq. 996", subscribers = {} }, -- 996   
		{ name = "Freq. 997", subscribers = {} }, -- 997   
		{ name = "Freq. 998", subscribers = {} }, -- 998   
		{ name = "Freq. 999", subscribers = {} }, -- 999   
		{ name = "Policia 01", subscribers = {} }, -- 1000   
		{ name = "STAFF", subscribers = {} }, -- 1001 
		{ name = "Policia 02", subscribers = {} }, -- 1002 
		{ name = "Driftking", subscribers = {} }, -- 1003 
		{ name = "Triade", subscribers = {} }, -- 1004 
		{ name = "SAMU", subscribers = {} }, -- 1005 
		{ name = "Bennys", subscribers = {} }, -- 1006 
		{ name = "SportRace", subscribers = {} }, -- 1007 
		{ name = "Verdes", subscribers = {} }, -- 1008 
		{ name = "Vermelhos", subscribers = {} }, -- 1009 
		{ name = "Roxos", subscribers = {} }, -- 1010 
		{ name = "Midnight", subscribers = {} }, -- 1011 
		{ name = "Cosanostra", subscribers = {} }, -- 1012 
		{ name = "Yakuza", subscribers = {} }, -- 1013 
		{ name = "Salieri's", subscribers = {} }, -- 1014 
		{ name = "Taxista", subscribers = {} }, -- 1015 
		{ name = "Laranjas", subscribers = {} }, -- 1016 
		{ name = "Sinaloa", subscribers = {} }, -- 1017 
		{ name = "Irmandade", subscribers = {} }, -- 1018 
		{ name = "Judiciario", subscribers = {} }, -- 1019 
		{ name = "", subscribers = {} }, -- 1020 
		{ name = "", subscribers = {} }, -- 1021 
		{ name = "", subscribers = {} }, -- 1022 
		{ name = "", subscribers = {} }, -- 1023 
		{ name = "", subscribers = {} }, -- 1024 
		{ name = "", subscribers = {} }, -- 1025 
		{ name = "", subscribers = {} }, -- 1026 
		{ name = "", subscribers = {} }, -- 1027 
		{ name = "", subscribers = {} }, -- 1028 
		{ name = "", subscribers = {} }, -- 1029 
		{ name = "", subscribers = {} }, -- 1030 
		{ name = "", subscribers = {} }, -- 1031 
		{ name = "", subscribers = {} }, -- 1032 
		{ name = "", subscribers = {} }, -- 1033 
		{ name = "", subscribers = {} }, -- 1034 
		{ name = "", subscribers = {} }, -- 1035 
		{ name = "", subscribers = {} }, -- 1036

		{ name = "Chamada Celular", subscribers = {} }, -- Telefone
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone 
		{ name = "Chamada Celular", subscribers = {} }, -- Telefone
	}
};