CREATE TABLE IF NOT EXISTS `vrp_acoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(7,2) NOT NULL,
  `alta` DECIMAL(7,2) NOT NULL,
  `baixa` DECIMAL(7,2) NOT NULL,
  `fecha` DECIMAL(7,2) NOT NULL,
  `data` DATE NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));

CREATE TABLE IF NOT EXISTS `bolsa_jogador` (
  `user_id` INT NOT NULL,
  `valor` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`user_id`));
