resource_manifest_version "44febabe-d386-4d18-afbe-5e627f4af937"

ui_page "client/html/ui.html"
files {
	"client/html/ui.html",
	"client/html/styles.css",
	"client/html/scripts.js",
	"configNui.js",
	"client/html/debounce.min.js",
	"client/html/sweetalert2.all.min.js",
	"client/html/sweetalert2.all.min.js",
	"client/html/assets/icons/hkp7m10.png",
	"client/html/assets/icons/fiveseven.png",
	"client/html/assets/icons/microuzi.png",
	"client/html/assets/icons/thompson.png",
	"client/html/assets/icons/mtar21.png",
	"client/html/assets/icons/ak74.png",
	"client/html/assets/icons/m-hkp7m10.png",
	"client/html/assets/icons/m-fiveseven.png",
	"client/html/assets/icons/m-microuzi.png",
	"client/html/assets/icons/m-thompson.png",
	"client/html/assets/icons/m-mtar21.png",
	"client/html/assets/icons/m-ak74.png",
	"client/html/assets/icons/ecstasy.png",
	"client/html/assets/icons/metilenodioximetanfetamina.png",
	"client/html/assets/icons/glicerina.png",
	"client/html/assets/icons/cocaina.png",
	"client/html/assets/icons/benzocaina.png",
	"client/html/assets/icons/baseado.png",
	"client/html/assets/icons/seda.png",
	"client/html/assets/icons/maconha.png",
	"client/html/assets/icons/pecadehk.png",
	"client/html/assets/icons/projetodehk.png",
	"client/html/assets/icons/pecadefive.png",
	"client/html/assets/icons/projetodefive.png",
	"client/html/assets/icons/pecadeuzi.png",
	"client/html/assets/icons/projetodeuzi.png",
	"client/html/assets/icons/pecadethompsom.png",
	"client/html/assets/icons/projetodedethompsom.png",
	"client/html/assets/icons/pecademtar.png",
	"client/html/assets/icons/projetodemtar.png",
	"client/html/assets/icons/pecadeak.png",
	"client/html/assets/icons/projetodeak.png",
	"client/html/assets/icons/capsuladehk.png",
	"client/html/assets/icons/projetil.png",
	"client/html/assets/icons/polvora.png",
	"client/html/assets/icons/capsuladefive.png",
	"client/html/assets/icons/capsuladeuzi.png",
	"client/html/assets/icons/capsuladethompsom.png",
	"client/html/assets/icons/capsulademtar.png",
	"client/html/assets/icons/capsuladeak.png",
	"client/html/assets/icons/mochila.png",
	"client/html/assets/icons/pano.png",
	"client/html/assets/icons/linha.png",
	"client/html/assets/icons/ziper.png",
	"client/html/assets/icons/colete.png",
	"client/html/assets/icons/kevlar.png",
	"client/html/assets/icons/placabalistica.png",
	"client/html/assets/icons/energetico.png",
	"client/html/assets/icons/taurina.png",
	"client/html/assets/icons/garrafa-vazia.png",
	"client/html/assets/icons/cafeina.png",
	"client/html/assets/icons/pacoteak.png",
	"client/html/assets/icons/pacotefive.png",
	"client/html/assets/icons/pacotehk.png",
	"client/html/assets/icons/pacotemtar.png",
	"client/html/assets/icons/pacotethomson.png",
	"client/html/assets/icons/pacoteuzi.png",
}

client_scripts {
	"lib/Proxy.lua",
	"@vrp/lib/utils.lua",
	"lib/Tunnel.lua",
	"config.lua",
	"client.lua",
	"receitas.lua",
	"locais.lua",
	"funcoes.lua"
}

server_scripts {
	"@vrp/lib/utils.lua",
	"config.lua",
	"server.lua"
}
